### ISSUE TITLE
cell language menu is too wide in advanced mode

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1053]
![screen shot 2015-01-15 at 3 08 57 pm](https://cloud.githubusercontent.com/assets/963093/5765587/c677b124-9cc8-11e4-94f4-ce066b8d47be.png)

by comparison, the regular menu:
![screen shot 2015-01-15 at 3 12 03 pm](https://cloud.githubusercontent.com/assets/963093/5765603/e19bb590-9cc8-11e4-9dc6-f5a053e4acca.png)

**Comment by buob** [comment]
Unfortunately this is due to the approach of all dropdowns like this:

https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/components/notebook/cell-directive.js#L194

https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/components/notebook/codecelloutputmenu-directive.js#L75

I tried re-architecting this a while back, to no avail.  If we treat it like a normal dropdown it gets covered by elements following it.

I'd recommend leaving this issue open, and marking with `wontfix` for now until we find a better solution to the problem.

**Comment by buob** [comment]
Or I can investigate a better solution now, I _think_ we could calculate the width by rendering it with 0 opacity and then setting the left attribute.  Still kinda hacky, but more invisible.
