### ISSUE TITLE
import/export function from notebook to another

### ISSUE THREAD

**Issue by moshir** [twosigma/beakerx#1057]
Simple question : 
can I import a notebook code from another notebook.
Suppose I have notebook1 with a javascript cell inside :
`module.exports = function mysum (a, b){ return a+b}`

Now, i want to use `mysum` from notebook2, is it possible ?

**Comment by scottdraves** [comment]
Hi Moshir, thanks for your question.  We don't support loading code from another notebook because we figure once you are reusing code, you are best off using the native import/library/package system for whichever language you are using.  In the case of Javascript, that's a little tricky but you can do it as described here: https://github.com/twosigma/beaker-notebook/issues/421
