### ISSUE TITLE
Include nginx in Windows install package

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#109]
Let's include nginx so that users don't have to manually install it.

**Comment by scottdraves** [comment]
This is just one of like 8 things users have to install.  I don't see that the nginx install is that much different or worse than the others.  on mac, yes i did hack it out.  but only because on mac, nginx required xcode.  it was a hack until we make a real installer that's where we include the dependencies.  so let's defer this until we make an installer, and do all of them in one fell swoop.

**Comment by jchendy** [comment]
Sure. I wasn't trying to suggest any particular urgency on this.

**Comment by scottdraves** [comment]
this was done in v0.55
