### ISSUE TITLE
Open .ipynb from URL is broken

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#134]
Try opening a notebook such as: http://atwallab.cshl.edu/teaching/QBbootcamp3.ipynb

I get this:

HTTP ERROR: 404
Problem accessing /rest/httpProxy/load. Reason:

```
Not Found
```

**Comment by anglee** [comment]
That error is actually coming from the iruby menu plugin. Yes, it need to be updated to use the new server endpoint. However, this exposed a greater problem was, the iruby menu plugin is registering a file opener that conflict with the ipython menu plugin. Before that is fixed, all ipython notebook will be using the iruby plugin instead of ipython plugin.
