### ISSUE TITLE
gulp does not report errors for missing files

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1385]
if you edit a script tag in index_template.html to be garbage, and then run the app, no error is reported, it is silently ignored.

**Comment by samccone** [comment]
yeah this is to be expected since gulp has no knowledge of the script tags in `index_template.html`, since they are hard coded tags in the actual markup.

If we had a build phase that mixed down all of the JS files into a single file and then used that one JS file on the front end, that should resolve this issue.

What did you have in mind?
