### ISSUE TITLE
diagrams

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1396]
should add something like https://github.com/tgdwyer/WebCola or https://github.com/cpettitt/dagre-d3
for automatic layout of diagrams.  also possible to do something more like visio eg http://www.jointjs.com/ https://github.com/sporritt/jsplumb/ seems related

http://www.draw2d.org/draw2d/ and http://gojs.net/latest/index.html look cool but not open source.

**Comment by patdohere** [comment]
There is some similar tools in the JavaScript world that take a markdown approach to describing and generating flow charts and diagrams.

Mermaid does both Flowcharts and Sequence diagrams - https://knsv.github.io/mermaid/#mermaid
Flowcharts - http://flowchart.js.org/
Sequence Diagrams - https://bramp.github.io/js-sequence-diagrams/

**Comment by scottdraves** [comment]
thanks for the ideas!

**Comment by patdohere** [comment]
I was wondering if I wanted to fork and try building support for Mermaid in.  Would it be preferred to be built as a new cell type?  Because mermaid allows you to quickly draw diagrams using a markdown like syntax.

```
 %% Subgraph example
 graph TB
         subgraph one
         a1-->a2
         end
         subgraph two
         b1-->b2
         end
         subgraph three
         c1-->c2
         end
         c1-->a2
```

Will produce the following diagram.
![screen shot 2016-04-12 at 10 00 03 am](https://cloud.githubusercontent.com/assets/1388836/14468633/6698360c-0095-11e6-8a56-f8ba89ab929f.png)

**Comment by scottdraves** [comment]
if you add it like tex (input and output types) then you could write it manually in a cell, or generate diagrams programmatically. see:

core/src/main/web/plugin/evaluator/latex.js
core/src/main/web/outputdisplay/bko-latex.js

**Comment by scottdraves** [comment]
btw, if you do this I would be interested in a pull request!  we have a standard CLA...
