### ISSUE TITLE
Setting up Python and IPython

### ISSUE THREAD

**Issue by hx2A** [twosigma/beakerx#1435]
Can you provide more information about how to setup Python and IPython in Beaker? Can you provide more working examples for how to set up the beaker.pref.json file? My IPython executable is in /usr/local/bin/ipython. What should my pref file look like?

Why does the install script create a virtual environment? Should I activate that before starting Beaker? Should my pref file point to that Python installation?

Also, I discovered if you have an extra } in that file you get a bizarre exception. Can you check for badly formed JSON files and inform the user?

**Comment by hx2A** [comment]
I now have Python3 working with this:

{
  "languages" : {
    "IPython" : {
      "path" : "/usr/local/bin"
    },
    "Python3" : {
      "path" : "/home/jim/py3k/bin"
    }
  },
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : true
}

Can't get IPython to work though.

What exactly is it looking for in that path? If I knew how to test this it would be easier to get it to work.

**Comment by scottdraves** [comment]
Thanks for the report.  Indeed we should have a better error message when beaker.pref.json has a syntax error.  I filed that here: https://github.com/twosigma/beaker-notebook/issues/1436

The documentation for the preferences file is here: https://github.com/twosigma/beaker-notebook/wiki/Language-Preferences

If that is indeed the location of your ipython then your prefs look fine.  What kind of computer and OS do you have and how did you install IPython?  What do you get from `/usr/local/bin/ipython --version`?  What happens if you run `/usr/local/bin/ipython noteobok`?  When you say IPython doesn't work, how does it fail?

**Comment by toryhaavik** [comment]
i'm having the same issue with ipython.

os: ubuntu 14.04
installed ipython with `apt-get install ipython`

```
% which ipython
/usr/bin/ipython

% /usr/bin/ipython --version
1.2.1
```

config:

```
{
  "languages" : {
    "IPython" : {
      "path" : "/usr/bin"
    }
  },
  "pref-format" : "1",
  "advanced-mode" : true,
  "allow-anonymous-usage-tracking" : true
}
```

"ipython not working" means i get this modal:

```
Language Error
Failed to start IPython.

Did you install it according to the instructions on BeakerNotebook.com?

If you already have it, then edit your preferences file to help Beaker find it on your system, and then restart Beaker and try again.

Any other languages in your notebook should still work.
```

**Comment by scottdraves** [comment]
Thanks Tory.
What do you get from `ipython notebook` on the command line?

**Comment by scottdraves** [comment]
btw, that's not how we recommend you install ipython (hence the old version, they are up to 3.0).
the instructions say to follow install-dependencies.sh which has:

```
sudo apt-get install -y python-pip python-dev python-yaml
sudo pip install ipython jinja2 tornado pyzmq pandas jsonschema
sudo apt-get install -y python-matplotlib python-scipy
```

that said, it should still work with an old version.  i wonder if you install is complete though...

**Comment by toryhaavik** [comment]
very interesting, thanks.  i had been using ipython notebook (from the apt-get install) prior to downloading beaker and it had worked.  now when i run it, it tells me `could not start notebook. please install python-notebook`.

i'll back out my apt-get install and install using pip.  i couldn't find docs on recommended install, did i miss them?

**Comment by toryhaavik** [comment]
oh, now that i think about it, of course i ran install-dependencies.sh.  i pulled out the ipython in /usr/bin and now i have ipython in /usr/local/bin, and beaker properly picks it up.  so lesson learned, don't apt to install ipython, or manually fix your $PATH after installing it using pip.

**Comment by scottdraves** [comment]
great thanks.

**Comment by scottdraves** [comment]
added to faq: https://github.com/twosigma/beaker-notebook-www/commit/510750ab51c5d56a5c5772eff119601ddf541233

**Comment by hx2A** [comment]
Thank you for the responses. I just got back from a weekend away and I was able to get it to work. I had the same problem as Tony, where I was getting the "could not start notebook" error. I had to remove some Ubuntu Python packages (in my case, ipython, tornado and pyzmq) and install the newer versions with pip install.

Now I have IPython and Python3 both working, and I understand what I need to do to get other languages to work.

I have one more question about making this easier to use. When I start beaker, I get this error message:

[alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

Why does it have to write the logs to there? If it isn't too much trouble, can that log file directory be configurable in one of the json files?

**Comment by scottdraves** [comment]
glad you are all set.
the log isn't written there, that's a spurious report by nginx.
thanks again.

**Comment by ibarani** [comment]
I am running on Mac OS X Yosemite and cannot get my IPython to initialize in Beaker Notebook. I followed the instructions here and even modified the preferences file. I even updated and reinstalled Acaconda.  I have the Accelerate and IOPro add-ons for Anaconda... not sure if this is causing problems. I removed the entire anaconda directory at one point and did a clean install but to no avail. That said, I am running zsh shell but I was under the impression that preferences file will fix this... is this not true? Can you please assist? Thank you in advance.

**Comment by scottdraves** [comment]
Thanks for the feedback, Igor.

Can you please show us the contents of your beaker.pref.json file, and also how you run IPython from a terminal, and the result of "which ipython" in your terminal?

**Comment by scottdraves** [comment]
Also, any JavaScript console messges and messages from Beaker in the Console application.

**Comment by ibarani** [comment]
Thank you for your quick reply.  My beaker.pref.json file is below:

{
  "pref-format" : "1",
  "allow-anonymous-usage-tracking" : true,
  "languages" : {
    "IPython" : {
      "path" : "/Users/ibarani/anaconda/bin"
    },
    "Python3" : {
      "path" : "/Users/ibarani/anaconda/envs/py3k/bin"
    }
  },
  "advanced-mode" : false,
  "edit-mode" : "default"
}

My terminal output:

Last login: Mon Jul 27 17:29:58 on ttys000

~
▶ ipython
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42)
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: quit

~
▶ which ipython
/Users/ibarani/anaconda/bin/ipython

~
▶

.ijb

_Electronic mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues._

NOTE:  The information in this message may be privileged and confidential
and protected from disclosure.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited.  If
you have received this communication in error, please notify the sender

## immediately by replying to the message and deleting it from your computer.

**Comment by ibarani** [comment]
Below are the console messages from the start of the Beaker Application.
(see attached)

.ijb

_Electronic mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues._

NOTE:  The information in this message may be privileged and confidential
and protected from disclosure.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited.  If
you have received this communication in error, please notify the sender

## immediately by replying to the message and deleting it from your computer.

**Comment by scottdraves** [comment]
The attachments are not coming through when you email to the bug.  Please drag-and-drop them into the web page.

**Comment by scottdraves** [comment]
Also, what is the output of "which ipython"?

**Comment by ibarani** [comment]
My apologies:

7/27/15 6:14:23.096 PM Beaker[5361] Beaker App start JVM and launch browser
7/27/15 6:14:23.932 PM Beaker[5361] starting nginx instance
(/Applications/Beaker.app/Contents/Resources/dist/nginx)
7/27/15 6:14:24.031 PM Beaker[5361] [main] INFO
org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
7/27/15 6:14:24.597 PM Beaker[5361] [main] INFO
org.eclipse.jetty.server.AbstractConnector - Started
SelectChannelConnector@127.0.0.1:8802
7/27/15 6:14:24.615 PM Beaker[5361]
Connecting to http://127.0.0.1:8801/
7/27/15 6:14:24.000 PM kernel[0] Google Chrome He (map: 0xffffff809ce55000)
triggered DYLD shared region unnest for map: 0xffffff809ce55000, region
0x7fff8d200000->0x7fff8d400000. While not abnormal for debuggers, this
increases system memory footprint until the target exits.
7/27/15 6:14:25.000 PM kernel[0] Google Chrome He (map: 0xffffff80b6ac5d20)
triggered DYLD shared region unnest for map: 0xffffff80b6ac5d20, region
0x7fff8d200000->0x7fff8d400000. While not abnormal for debuggers, this
increases system memory footprint until the target exits.
7/27/15 6:14:25.000 PM kernel[0] Google Chrome He (map: 0xffffff80a62ca2d0)
triggered DYLD shared region unnest for map: 0xffffff80a62ca2d0, region
0x7fff8d200000->0x7fff8d400000. While not abnormal for debuggers, this
increases system memory footprint until the target exits.
7/27/15 6:14:26.000 PM kernel[0] Google Chrome He (map: 0xffffff80a62caf00)
triggered DYLD shared region unnest for map: 0xffffff80a62caf00, region
0x7fff8d200000->0x7fff8d400000. While not abnormal for debuggers, this
increases system memory footprint until the target exits.
7/27/15 6:14:42.000 PM kernel[0] Google Chrome He (map: 0xffffff80a62caf00)
triggered DYLD shared region unnest for map: 0xffffff80a62caf00, region
0x7fff8d200000->0x7fff8d400000. While not abnormal for debuggers, this
increases system memory footprint until the target exits.
7/27/15 6:14:43.000 PM kernel[0] Google Chrome He (map: 0xffffff80a62ca2d0)
triggered DYLD shared region unnest for map: 0xffffff80a62ca2d0, region
0x7fff8d200000->0x7fff8d400000. While not abnormal for debuggers, this
increases system memory footprint until the target exits.
7/27/15 6:14:46.000 PM kernel[0] Google Chrome He (map: 0xffffff80a24f7000)
triggered DYLD shared region unnest for map: 0xffffff80a24f7000, region
0x7fff8d200000->0x7fff8d400000. While not abnormal for debuggers, this
increases system memory footprint until the target exits.
7/27/15 6:14:53.438 PM python[5387] WARNING: The Gestalt selector
gestaltSystemVersion is returning 10.9.4 instead of 10.10.4. Use
NSProcessInfo's operatingSystemVersion property to get correct system
version number.
Call location:
7/27/15 6:14:53.438 PM python[5387] 0   CarbonCore
 0x00007fff849c52b7 ___Gestalt_SystemVersion_block_invoke + 113
7/27/15 6:14:53.438 PM python[5387] 1   libdispatch.dylib
0x00007fff8f5a2c13 _dispatch_client_callout + 8
7/27/15 6:14:53.438 PM python[5387] 2   libdispatch.dylib
0x00007fff8f5a2b26 dispatch_once_f + 117
7/27/15 6:14:53.438 PM python[5387] 3   CarbonCore
 0x00007fff8494e456 _Gestalt_SystemVersion + 987
7/27/15 6:14:53.438 PM python[5387] 4   CarbonCore
 0x00007fff8494d6e3 Gestalt + 144
7/27/15 6:14:53.438 PM python[5387] 5   libQtCore.4.8.6.dylib
0x0000000109526b16 _GLOBAL__I__Z8qVersionv + 22
7/27/15 6:14:53.438 PM python[5387] 6   ???
0x00007fff65acfceb 0x0 + 140734899223787
7/27/15 6:14:54.157 PM Beaker[5361] Running
0:
/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/ipythonPlugins/ipython/ipythonPlugin
1: 8804
7/27/15 6:14:54.388 PM Beaker[5361] Done starting IPython
7/27/15 6:14:54.412 PM Beaker[5361] nginx-stderr>2015/07/27 18:14:54
[error] 5393#0: *48 kevent() reported that connect() failed (61: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /770609a/ipython.763078736019/login HTTP/1.1", upstream: "
http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "
http://127.0.0.1:8801/beaker/"
7/27/15 6:14:54.467 PM Beaker[5361] nginx-stderr>2015/07/27 18:14:54
[error] 5393#0: *48 kevent() reported that connect() failed (61: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /770609a/ipython.763078736019/login HTTP/1.1", upstream: "
http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "
http://127.0.0.1:8801/beaker/"
7/27/15 6:14:54.497 PM Beaker[5361] nginx-stderr>2015/07/27 18:14:54
[error] 5393#0: *48 kevent() reported that connect() failed (61: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /770609a/ipython.763078736019/login HTTP/1.1", upstream: "
http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "
http://127.0.0.1:8801/beaker/"
7/27/15 6:14:54.538 PM Beaker[5361] nginx-stderr>2015/07/27 18:14:54
[error] 5393#0: *48 kevent() reported that connect() failed (61: Connection
refused) while connecting to upstream, client: 127.0.0.1, server: ,
request: "GET /770609a/ipython.763078736019/login HTTP/1.1", upstream: "
http://127.0.0.1:8804/login", host: "127.0.0.1:8801", referrer: "
http://127.0.0.1:8801/beaker/"
7/27/15 6:14:54.566 PM Beaker[5361] IPython-stderr>[I 18:14:54.565
NotebookApp] Writing notebook server cookie secret to
/Users/ibarani/.beaker/v1/nginx3809506683501264035/profile_beaker_backend_IPython/security/notebook_cookie_secret
7/27/15 6:14:54.566 PM Beaker[5361] IPython-stderr>[I 18:14:54.566
NotebookApp] Using MathJax from CDN:
https://cdn.mathjax.org/mathjax/latest/MathJax.js
7/27/15 6:14:54.589 PM Beaker[5361] IPython-stderr>[I 18:14:54.587
NotebookApp] Serving notebooks from local directory:
/Applications/Beaker.app/Contents/Resources/dist
IPython-stderr>[I 18:14:54.587 NotebookApp] 0 active kernels
7/27/15 6:14:54.589 PM Beaker[5361] IPython-stderr>[I 18:14:54.588
NotebookApp] The IPython Notebook is running at: http://127.0.0.1:8804/
IPython-stderr>[I 18:14:54.588 NotebookApp] Use Control-C to stop this
server and shut down all kernels (twice to skip confirmation).
7/27/15 6:14:54.630 PM Beaker[5361] IPython-stderr>[I 18:14:54.629
NotebookApp] 302 POST /login?next=%2F (127.0.0.1) 0.74ms
7/27/15 6:14:54.643 PM Beaker[5361] IPython-stderr>[W 18:14:54.642
NotebookApp] Blocking Cross Origin API request.  Origin:
http://127.0.0.1:8801, Host: 127.0.0.1:8804
7/27/15 6:14:54.649 PM Beaker[5361] IPython-stderr>[W 18:14:54.648
NotebookApp] 404 POST /api/sessions (127.0.0.1) 6.76ms referer=
http://127.0.0.1:8801/beaker/

.ijb

_Electronic mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues._

NOTE:  The information in this message may be privileged and confidential
and protected from disclosure.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited.  If
you have received this communication in error, please notify the sender

## immediately by replying to the message and deleting it from your computer.

**Comment by ibarani** [comment]
▶ which ipython
/Users/ibarani/anaconda/bin/ipython

.ijb

_Electronic mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues._

NOTE:  The information in this message may be privileged and confidential
and protected from disclosure.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited.  If
you have received this communication in error, please notify the sender

## immediately by replying to the message and deleting it from your computer.

**Comment by scottdraves** [comment]
What web browser are you using and what version of Beaker?

**Comment by ibarani** [comment]
Chrome and Beaker 1.3.3

.ijb

_Electronic mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues._

NOTE:  The information in this message may be privileged and confidential
and protected from disclosure.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited.  If
you have received this communication in error, please notify the sender

## immediately by replying to the message and deleting it from your computer.

**Comment by scottdraves** [comment]
Thanks.  The relevant line from the log is:

```
7/27/15 6:14:54.643 PM Beaker[5361] IPython-stderr>[W 18:14:54.642 NotebookApp] Blocking Cross Origin API request.  Origin: http://127.0.0.1:8801, Host: 127.0.0.1:8804
```

We have seen this before:
https://github.com/twosigma/beaker-notebook/issues/1952
But we thought it was fixed.
Can you try Firefox?

**Comment by ibarani** [comment]
Will try in a few mins... Do you know the cause of this? Could it be Google
Chrome extensions?

**Comment by scottdraves** [comment]
Yes, something in the HTTP headers is goofed up.  Trying with an incognito chrome window would be a good test too.

**Comment by ibarani** [comment]
I just tried firefox but get "Ipython initialization failed. ERROR: A"

**Comment by scottdraves** [comment]
Quite baffling.... thanks for all the answers.  What do you get from "ipython --version"?

**Comment by ibarani** [comment]
3.2.1

.ijb

_Electronic mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues._

NOTE:  The information in this message may be privileged and confidential
and protected from disclosure.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited.  If
you have received this communication in error, please notify the sender

## immediately by replying to the message and deleting it from your computer.

**Comment by ibarani** [comment]
I have the same situation on two other Macs that I own. I am able to get
just about everything else to work except for iPython. I am happy to do a
shared screen session with you tomorrow (Tuesday) if you think that could
help.

.ijb

_Electronic mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues._

NOTE:  The information in this message may be privileged and confidential
and protected from disclosure.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited.  If
you have received this communication in error, please notify the sender

## immediately by replying to the message and deleting it from your computer.

**Comment by scottdraves** [comment]
Thanks Igor.  I can reproduce.  The problem appeared with IPython 3.2.1.
You can workaround it by going back to 3.2.0.

**Comment by scottdraves** [comment]
https://github.com/ipython/ipython/commit/1415a9710407e7c14900531813c15ba6165f0816

**Comment by scottdraves** [comment]
That breaks this call to api/sessions: https://github.com/twosigma/beaker-notebook/blob/master/plugin/ipythonPlugins/src/dist/ipython/ipython.js#L119

need to add proxy_set_header to these rules:
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/java/com/twosigma/beaker/core/rest/PluginServiceLocatorRest.java#L111

**Comment by ibarani** [comment]
Thank you.

Do you know how to rollback ipython? I am not sure I know how. Is this bug
going to be fixed with future versions of ipython?

**Comment by scottdraves** [comment]
issue this command:

```
conda install ipython=3.2.0
```

this is actually a bug-fix in ipython.  beaker needs to follow suit.  we'll release a new version shortly.

**Comment by ibarani** [comment]
Thank you. Everything seems to be working now.

.ijb

_Electronic mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues._

NOTE:  The information in this message may be privileged and confidential
and protected from disclosure.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited.  If
you have received this communication in error, please notify the sender

## immediately by replying to the message and deleting it from your computer.

**Comment by ibarani** [comment]
Sorry. One last thing... do I have to do anything specific to start
Python3?  It does not seem to start as easily as IPython.

.ijb

_Electronic mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues._

NOTE:  The information in this message may be privileged and confidential
and protected from disclosure.  If the reader of this message is not the
intended recipient, you are hereby notified that any dissemination,
distribution or copying of this communication is strictly prohibited.  If
you have received this communication in error, please notify the sender

## immediately by replying to the message and deleting it from your computer.

**Comment by scottdraves** [comment]
filed at https://github.com/twosigma/beaker-notebook/issues/2003

**Comment by scottdraves** [comment]
please email me or our main feedback alias on the website to debug Python3.
