### ISSUE TITLE
add search and replace feature

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1466]

**Comment by choct155** [comment]
Just bumping the request.  It would be a nice addition to a solid product.

**Comment by scottdraves** [comment]
thank you!  agreed.

**Comment by scottdraves** [comment]
design:
1) add item to notebook menu "Search and replace...", it should have a keybinding
2) when selected, a persistent panel appears (placement TBD).  panel has "x" close button.
3) panel has a dialog with search-for text field, replace-with text field, search button, back button, replace button, and replace-all button.
4) search field updates as you type, highlighting all matches and scrolling to the 1st one.
search button scrolls to next match, back button to previous, replace button acts on current match and moves to next match, replace all acts on all matches.

**Comment by klstack3** [comment]
Hey Scott, some quick initial thoughts: http://wzeecq.axshare.com

I’ve placed the find and replace link under the “notebook” menu as it seems to be the closest thing we currently have to “edit” where this sort of functionality would typically be found. I think the bottom bar placement could work but might take up a fair bit of real estate, what if it was a drag and drop menu that users could adjust to their liking? I’ve mocked up a couple limited functionality prototypes at the link.

**Comment by scottdraves** [comment]
thx.  base menu solution looks good, 
the text boxes don't have to be so big (def 1 line), remove the title & explanatory text too.
case sensitive and selected cell vs whole notebook are good ideas (the later should be grayed out if the cursor was not in a cell).  also does need a "previous" button.

if you press ESC then it closes, if you press enter in the find box then it goes next, if you press enter in the replace box then it replaces current and moves to next.

**Comment by klstack3** [comment]
For sure, the explanatory text probably isn't necessary and I see why you might want to remove the title though I think the title should remain to help maintain hierarchy and the distinction that this is a separate module... 

I also wonder if users will want to find and replace large sections of code or text and if the find and replace cells should expand with input for easier viewing? Not sure how often that would be a concern or if they’re more likely to try to replace smaller elements... but since it's code it may take up a couple of lines.

I also left room for more filters if there is something else you think they may be likely to want to ignore or customize in the search.

A revised version: http://wzeecq.axshare.com

**Comment by scottdraves** [comment]
cool thx that's close enough.  large sections of code generally not used here, no need to worry about expansion.  someday we'll have more switches (like regexps) so good to know there is room for them.

**Comment by scottdraves** [comment]
note we have a similar UI element already you can reuse.
from the view menu, select "Show stdout/err" to see it.
