### ISSUE TITLE
apply margin fix to regular code cells

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#1497]
i think this: https://github.com/twosigma/beaker-notebook/commit/ae250664ac26c0ceab27b5ed969cb8c797dcdeb2

improvement should be applied to regular code cells that also have some of the problems that markdown cells did.

**Comment by buob** [comment]
After investigating, the fix wouldn't apply as cleanly to codecells because the padding would change between advanced and normal mode.   We'd not only have to watch changes to advanced mode and refresh every codemirror, but we'd also have to render codemirror after the correct padding was applied for the appropriate mode (right now it would flash between thinner and thicker).  Because it's a refactor, we'd be trading complexity in one area for another.  Tabling for now...
