### ISSUE TITLE
Font discrepancy throughout platforms

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#1988]
Fonts are inconsistent throughout platforms. The default fonts for 'monospace', which is heavily used by CodeMirror is different between OSX and Linux. We probably have to get rid of 'monospace' and use a font that is included with Beaker. Options are:
- Using a font that is known to be available on all platforms, which due to Linux will probably be an open source font like Nimbus.
- Enforce Courier, which is what we have seen so far on OSX and Windows. Will require a dependency on Linux.

**Comment by DiegoAlbertoTorres** [comment]
This will also fix #1947.

**Comment by DiegoAlbertoTorres** [comment]
TwoSigma seems to recommend Roboto as a font for web applications. Roboto Mono is licensed under Apache. Seems like a good choice?

**Comment by scottdraves** [comment]
for output values (not html), i am getting menlo as my typeface.
i can't think of a reason why this would be different from the code font.
prob should be roboto mono as well.

**Comment by scottdraves** [comment]
in particular see this problem: https://github.com/twosigma/beaker-notebook/issues/2353

it's not clear what's going on.  changing from roboto mono to ubuntu mono fixed the problem on ubuntu with chrome 44.  but not on mac with chrome 45.
firefox does not exhibit the problem at all.
i have a feeling it's related to the matching parens highlight because when it does that (when i type the close ])
the text wiggles for a fraction of a second and that's when the cursor jumps to the wrong location.

i have reverted all these font changes (https://github.com/twosigma/beaker-notebook/pull/2376) until we can understand what's going on and get this right.

**Comment by scottdraves** [comment]
this too: https://github.com/twosigma/beaker-notebook/issues/2371
