### ISSUE TITLE
need spinner when publishing a notebook

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2195]
Add an upload spinner

**Comment by scottdraves** [comment]
there may be a spinner, but it's in the window behind.  it needs to be front and center, in the dialog where you are posting from.

**Comment by grin** [comment]
<img width="614" alt="123d_bkr" src="https://cloud.githubusercontent.com/assets/12468/9533223/dd71eb1c-4d10-11e5-9897-5022077f2e54.png">

@scottdraves I reused the standard beaker spinner...didn't put it in the center because it didn't look good there, chose a different spot. Let me know what you think...

implemented in https://github.com/twosigma/beaker-notebook/pull/2218 /  d4878ec

**Comment by scottdraves** [comment]
:+1:

**Comment by ildipo** [comment]
merged
