### ISSUE TITLE
when publishing category should be optional

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2199]
What about having a Misc category where everything you don't set goes in?

**Comment by scottdraves** [comment]
instead of "Misc" it should be "None".
also, the description needs to be optional.

**Comment by planyon** [comment]
The publications that have no categories can just be listed when the user clicks on the "All" category in the tree.

I do think that forcing the user to provide some contextual information about the notebook -- either a category or description -- will make the experience of browsing through the publication site better. Otherwise users will have little to go on, besides clicking in to the publication and reading the cells, before they'll know if the publication is something they are interested in.

**Comment by scottdraves** [comment]
never force a user to do soemthing they don't want to do.

**Comment by grin** [comment]
implemented in: https://github.com/twosigma/beaker-notebook/pull/2274
