### ISSUE TITLE
after publishing a notebook open it in a new tab

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2252]
When publication upload is completed a new tab should open with the new published notebook inside it

**Comment by grin** [comment]
@ildipo this ended up quite tricky to get working...see my initial attempt, it "almost" works: https://github.com/twosigma/beaker-notebook/commit/c131af11ec7eda900df94108706fdc82798645aa

First, notice how opening a new tab is a two-step process:
1. before sending the publish request we open a new tab: `var tab = $window.open(bkPublicationApi.getBaseUrl())`
2. after we get a response we update the newly opened tab to show the actual publication: `tab.location = bkPublicationApi.getBaseUrl() + '/#/publications/' + pub['public-id']`

This is necessary to prevent built-in browser popup blockers from blocking the publication tab. If I simply try to open a new tab after receiving the successful publication response the tab will be blocked. This is because browsers only allow opening new windows/tabs as a direct result of user action. In javascript this means that new window/tab can be only opened if `window.open` is called in click or submit handlers but if it is called asynchronously or delayed it will get blocked. To work around this I first do the step 1 in a submit handler and then once the publication id is returned I update the location in the publication tab. This works quite well. but there is another issue now caused by calling `bkHelper.saveNotebook()` prior to sending the api publish request...if the notebook isn't saved to disk when I try to publish it beaker will show the file modal and will wait for user to select a file for saving the notebook...but the file selection modal will be shown after the step 1 and it will be block beaker from getting to step 2.

My question is, do we need to call `bkHelper.saveNotebook()` before publishing a notebook? We are calling it in two locations:
- save before publishing: https://github.com/twosigma/beaker-notebook/blob/c131af11ec7eda900df94108706fdc82798645aa/core/src/main/web/app/mainapp/components/publication/publication.js#L176 
- save after creating a new publication to make sure the publication id is included in the notebook data: https://github.com/twosigma/beaker-notebook/blob/c131af11ec7eda900df94108706fdc82798645aa/core/src/main/web/app/mainapp/components/publication/publication.js#L156

**Comment by ildipo** [comment]
I think we can avoid saving before publishing

**Comment by scottdraves** [comment]
yes please skip saving!
