### ISSUE TITLE
Feature request: saving cell data

### ISSUE THREAD

**Issue by tomlagatta** [twosigma/beakerx#226]
This might be out of your control. Currently, when I read a certain data file in R, the loading takes about 30 seconds. If I rerun the cell, the file loads again completely, which takes another 30 seconds.

Would it be possible for Beaker to recognize that the data file hasn't changed, and use the data in memory rather than reloading it from disk?

**Comment by jchendy** [comment]
Unfortunately, that's not the type of thing we're likely to work on. It would be more appropriate for that type of functionality to be built into the R libraries rather than the editor.

However, things like this are basically the whole point of notebooks. You can have one cell that reads the data file and another cell that does your processing. That way you can edit and rerun the second cell as much as you want without ever reading the data again.

**Comment by tomlagatta** [comment]
Got it. Thanks, Jeff!
