### ISSUE TITLE
Plot of object class 'phylo' crashes R front end

### ISSUE THREAD

**Issue by Rom1Garnier** [twosigma/beakerx#2319]
Hi, 

I realize that this is really a specific issue that I might be the only person interested in, but it may be showing some underlying instability with R graphics handling. 

I am working in R using phylogenetic data, using the packages 'ape' and 'phytools' (both freely available from CRAN). It is straightforward to import a phylogenetic tree in Newick format (read.newick) and then to obtain a plot of this tree using the plot() command. 

The code would look something like that: 

library(ape)
library(phytools)

tree<-read.newick('beaker_tree.txt')
tree_clean<-collapse.singles(tree)
plot(tree_clean)

This code works in R. Importing the object 'tree' works perfectly well in Beaker, and manipulating the object is not a problem either. 
However, the 'plot(tree)' seems to break R front end in Beaker. I immediately get a pop-up "R for Windows front-end has stopped working" and the only option is to close the program and then restart Beaker. 

An example of tree in Newick format can be found here: https://gist.github.com/Rom1Garnier/a0d28de2c6f925161c33#file-beaker_tree-txt

**Comment by scottdraves** [comment]
thanks, i'll try this out tomorrow and see if it works.
we have fixed some bugs in R plotting since 1.3.4...

**Comment by Rom1Garnier** [comment]
For the record, I am running Beaker 1.3.4.

**Comment by scottdraves** [comment]
still a bug: https://pub.beakernotebook.com/#/publications/55f350ff-981b-4e0e-8372-d346da90ac14

**Comment by scottdraves** [comment]
The problem here is phylo crashes the SVG driver in R.  Beaker is not involved.
That said, in order to work around this, Beaker could allow you to swap in another output driver, like PNG, so you can fallback in a situation like this.
The above commit does that, but it has trouble identifying when output was produced, since the driver seems to write PNG files even for non-graphical output, whereas the SVG driver writes no file at all if it has no output.  We need more.
