### ISSUE TITLE
[Native Beaker] About Beaker window

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2389]
should be native top-level, and at least on mac it should be moved to the Beaker menu, 1st item.

**Comment by alice-kroch** [comment]
In this article i’m going to explain why current Beaker electron application doesn’t work properly and how we should  make this application work. 
Current Beaker electron application use next scheme: it assembles web application source and copies it into electron’s distributive directory. The native electron application code is not complicated and not full-developed. It only creates base features and open native window with the given application URL (such as you can see it in browser). That’s it. So that current Beaker electron application doesn’t load angularjs at all, it only use source that has been copied from core and opens application URLs in window wrap. Such solution has lot of disadvantages: some of angularness features doesn’t work (some two-way data bindings concepts are broken), we can't create and develop native electron windows with using of angularjs and we can’t use electron core services in cope with angularjs to build smart UI. Also it doesn’t allows to build native Beaker menu in the right way - currently menu is created in two different ways simultaneously, from core web application service and from core electron service (which duplicates and downgrades some necessary features).
The solution is to build Beaker electron application from the scratch with properly load of all necessary tools. That mean, that application will load and work with all the dependences and use source that not copied from main application into distribution directory but from it’s own core. Such solution requires to rework templates that we want to work properly in native windows (about, languages selection, publication etc.) because they use $modal service which is not suitable for electron application. Also this solution allows to build all necessary native application features.
The example of boilerplate can be found [there](https://github.com/Stephn-R/Electron-Angular-Boilerplate). Also some [example](https://scotch.io/tutorials/creating-desktop-applications-with-angularjs-and-github-electron) with base features.
