### ISSUE TITLE
Pub server - after publication

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#2393]
after publication when it opens the web page with the noteobok, strangely i am seeing the front page for several seconds before it redirects to the right notebook

**Comment by grin** [comment]
@ildipo opening the front page was a necessity to get this flow working, see my past explanation about why we need to open it: https://github.com/twosigma/beaker-notebook/issues/2252#issuecomment-138916836
to make it a little bit nicer I can craft a "please wait, loading a publication" page which we would open instead of the front page. Would that work for you? We have to open something prior to opening the actual publication to work around browser security restrictions (which I described in that previous comment).

**Comment by ildipo** [comment]
I think we should have a page that has the same outline as the publication and says 'Please wait, loading publication...'

**Comment by grin** [comment]
Fixed in https://github.com/twosigma/beaker-notebook/pull/2462
