### ISSUE TITLE
why is **.scss required?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2526]
https://github.com/twosigma/beaker-notebook/commit/5112dadf57b74acd1477aa95ff95c52001e38f4f

seems like it should be app.scss but this breaks CI

**Comment by mnavasiolava** [comment]
app.scss is not enough because we also need vendor.scss to be compiled and added to result beakerApp.js. 
If you don’t see errors in browser when define only  app.scss this means that you already have compiled vendor.css in temp folder beaker-notebook\core\src\main\web\app\temp (which unexpectedly is not cleaned during build process)

So we can use gulp.src([].concat(Path.join(rootPath, "app.scss"), Path.join(rootPath, "vendor.scss"))) or just leave Path.join(rootPath, "**.scss")

**Comment by scottdraves** [comment]
thank you.

ok please make a PR to compile only those 2 files, and also to delete the temp directory on "gradle clean".
