### ISSUE TITLE
UI jumps when featured row loads

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2594]
The Search & Nav appear first, at the top of the page,
but then jump down when the features load.
space for the features should be reserved.
OK to have a gap if there are none.

![beaker publications](https://cloud.githubusercontent.com/assets/963093/10261026/09db62ba-6953-11e5-9528-98a2512dd063.png)

**Comment by planyon** [comment]
@sethkrasnianski I know this is working much better on smaller screens, what can we do to improve it on larger ones? And could you please remind me why it's different between them?

**Comment by sethkrasnianski** [comment]
We could do what @scottdraves suggested and add a fixed height. That way there would never be a jump. The difference is the screen size. One's smaller and therefore the calculations to set the dimensions for the carousel's inner container & slides take a fraction of the time. On a 23" to 27" screen, they take slightly longer, so the rest of the dom is rendered before the featured publications finish calculating/rendering. This causes the featured pubs to push down the content rather than fading in with them (as they do on small screens).

Since we'll always have featured publications, except when we launch a new instance of publications, it may make sense to just make the height fixed so it's less rigid. However, I'll test it out locally to see if it works
