### ISSUE TITLE
Add: Use parameters from the command line

### ISSUE THREAD

**Issue by rafa2000** [twosigma/beakerx#2599]
On OSX, I tried:
/Application/Beaker.app/Contents/MacOS/Beaker .
The dot at the end should open the current directory (ala atom) and use it as the desired current project. Currently, it just open the application and use a default and path to open files.

**Comment by scottdraves** [comment]
Thanks for the suggestion.  We don't have the notion of "project", but with the Electron version of Beaker you can say `/Applications/Beaker.app/Contents/MacOS/Electron  ./somefile.bkr` and it runs the application and opens somefile.  In fact you can even just double click somefile or say `open ./somefile.bkr`.

It would be possible, if you gave it a directory instead of a file, we could set the default location for opening files to that directory, is that what you mean?

The current binary is being discontinued in favor of the Electron version, so we'll be adding features there.
