### ISSUE TITLE
'run all' in section menu is broken

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#261]
1) Open the tutorial notebook
2) Select the farthest-right bracket and choose 'run all'
3) Most of the cells don't produce any output, and now you can't even run cells normally

**Comment by melmac48** [comment]
@samccone can you verify this is fixed with the new UI updates? thnx

**Comment by scottdraves** [comment]
this is still a bug!

**Comment by anglee** [comment]
@scottdraves can you elaborate? what did you try? why did you change the title?

The original bug was about "Run all" cell menu item for the bk-notebook cell menu, which is different from the section cell menu. If you see an issue with the section cell menu, a new issue should be filed.

In the new UI, the notebook cell menu is gone. The only way to run all the cells in the notebook is to go to the Run menu in Nav bar and "Run all", I tested that on the tutorial notebook and didn't see an issue. 

I also tried run all from each of the section cells in the tutorial notebook and didn't see any issue either.

**Comment by scottdraves** [comment]
i changed the title because we don't have bracket menus anymore.
i tried the "run all" item on the section at the top of the tutorial titled "Beaker Tutorial" which i thought would run the whole tutorial but indeed, that section is actually only the first paragraph.
anyway, sounds like this is fixed which is great, closing it.  thanks for testing.
