### ISSUE TITLE
Publication server css bug?

### ISSUE THREAD

**Issue by DiegoAlbertoTorres** [twosigma/beakerx#2631]
So, not sure if this goes in this repository, but there seems to be a css bug in the new publication server in fullscreen mode:
The footer seems to have a very small width, so it is showing one character per line! This happens in Firefox but not in Chrome.

![test2](https://cloud.githubusercontent.com/assets/3867399/10329269/f234a0b2-6c8c-11e5-90c1-cf178852d0e9.jpg)
![test1](https://cloud.githubusercontent.com/assets/3867399/10329268/f234797a-6c8c-11e5-9fd4-2bb8bd36709b.jpg)

**Comment by scottdraves** [comment]
Thanks Diego, I can see that too.  There are some other ffox bugs as well:  only 2 featured notebooks on top instead of 3:

<img width="1100" alt="screen shot 2015-10-07 at 7 40 13 am" src="https://cloud.githubusercontent.com/assets/963093/10336491/24cf65a4-6cc7-11e5-99f5-a9d57fa91add.png">
<img width="1107" alt="screen shot 2015-10-07 at 7 40 54 am" src="https://cloud.githubusercontent.com/assets/963093/10336490/24ccf74c-6cc7-11e5-9908-39ac0b8110e1.png">

also the main list of notebooks is different:
<img width="672" alt="screen shot 2015-10-07 at 7 42 10 am" src="https://cloud.githubusercontent.com/assets/963093/10336523/52e12c8e-6cc7-11e5-9831-53a1bfca5d7c.png">
vs:
<img width="680" alt="screen shot 2015-10-07 at 7 42 17 am" src="https://cloud.githubusercontent.com/assets/963093/10336522/52df31ea-6cc7-11e5-98d6-c9b354e4b82a.png">

**Comment by sethkrasnianski** [comment]
Thanks :+1: 
Closing this. I broke it up into three issues to better track each bug.
