### ISSUE TITLE
blueimp-canvas-to-blob and blueimp-load-image maybe redundant

### ISSUE THREAD

**Issue by jonassmedegaard** [twosigma/beakerx#2649]
It seems at least parts of blueimp projects are embedded in FileAPI.js of ng-file-upload.

Please try if possible to reduce avoid those possibly redundant dependencies.

**Comment by scottdraves** [comment]
Not sure what you are suggesting here.  we have copies of the stuff downloaded from bower in our tree just to make us less dependent on their servers.  presumably you are replacing this with debian versions.
if there is a debian version of ng-file-upload then you can ignore ours and we are good, right?

**Comment by jonassmedegaard** [comment]
Quoting Scott Draves (2015-10-07 23:30:12)

> Not sure what you are suggesting here. we have copies of the stuff 
> downloaded from bower in our tree just to make us less dependent on 
> their servers.
> presumably you are replacing this with debian versions.
> if there is a debian version of ng-file-upload then you can ignore 
> ours and we are good, right?

It seems src/main/web/vendor/bower_components/ng-file-upload/FileAPI.js 
is a superset of 
core/src/main/web/vendor/bower_components/blueimp-canvas-to-blob/js/canvas-to-blob.js 
and 
core/src/main/web/vendor/bower_components/blueimp-load-image/js/load-image-ios.js 
- and possibly of other files below 
  core/src/main/web/vendor/bower_components/blueimp-load-image as well.

If ng-file-upload can be used for all (not only some) of the cases where 
blueimp-canvas-to-blob and blueimp-load-image is currently used, then 
that should give a slight speedup and slightly lower memory consumption.  
Benefit for me would be 2 packages less to package.

But you are right, we need not change anything here - nothing is broken, 
just (possibly) less optimized.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by maxyeg** [comment]
We have `blueimp-canvas-to-blob`, `blueimp-load-image` and `blueimp-tmpl` included, because they are dependencies of `jquery-file-upload`. 
https://github.com/blueimp/jQuery-File-Upload/blob/master/bower.json#L44

Beaker uses `jquery-file-upload` to import notebooks.
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/helpers/core.js#L216

What about `ng-file-upload`(which contains `FileAPI.js` and is superset of blueimp dependencies) - it was added to upload files when publishing notebooks.
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/utils/publication.js#L56

@scottdraves , please advice, should we remove one of them or should we keep everything as it is now.

**Comment by scottdraves** [comment]
let's use ng-file-upload like jonas suggests.
