### ISSUE TITLE
don't crop thumbnails

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2671]
they should be scaled down to fit (same amount in X and Y), leaving whitespace (centered).
this is for the regular metadata view.
in the featured view it should crop so the rectangle is filled.

**Comment by grin** [comment]
@scottdraves how "leaving whitespace" can be achieved without actually cropping thumbnails? Also, by "leaving whitespace" do you mean we should try to detect whitespace in all images (png, jpg) and crop images automatically so they don't show it? If yes, this problem seems a bit complex to solve in general.

If we want to have fine grained control over thumbnails maybe we should add a cropping step to our image upload flow, where a user could crop the image on his own using some js lib like http://fengyuanchen.github.io/cropper/ 
What do you think?

**Comment by scottdraves** [comment]
i think we should keep it simple and not introduce cropping UI.
i am not proposing looking into the image and deducing whitespace.
just treat the uploaded image as a unit.
do not crop it!  whatever the user sent up they want to see.
to make it fit into the space on the web page, introduce whitespace around what they uploaded,
either on top & bottom or on sides.

**Comment by grin** [comment]
:+1:

**Comment by grin** [comment]
Fixed in: https://github.com/twosigma/bunsen/pull/1266
