### ISSUE TITLE
thumbnails should be png not gif

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2726]
https://pub.beakernotebook.com/user/v1/attachments/560d93d4-5509-455b-8ed6-0fa4f960881b?variant=metadata

**Comment by grin** [comment]
yes, this seem broken...the original intention was to use the format of the uploaded image for thumbnails.

**Comment by grin** [comment]
Actually, all thumbnails preserve the original image format. Only incorrect file extension (".gif") gets appended by Chrome when a thumbnail image is downloaded and this happens because we don't set the correct content type for dynamic images and Chrome doesn't use the auto-detected image type internally when saving the file to disk. This works fine in Firefox.

Do we care about this file extension? Asking because we are not saving the image type to the db and currently there is no helper method exposed in the Clojure image lib we use for image resizing that would detect the type. So it's not a quick fix, but doable with some effort (if we care).

**Comment by ildipo** [comment]
can we save the image type in the DB?

**Comment by grin** [comment]
Fixed in https://circleci.com/gh/mojotech/bunsen/3015
