### ISSUE TITLE
add option for location of prefs and temp files

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2779]
this is especially important on windows in order to make a portable version of beaker that you can run from a thumb drive and does not modify any other volume.

this would be a cmd line, like --plugin-option and --public-server

**Comment by scottdraves** [comment]
--portable
puts what normally goes in ~/.beaker instead into the root of the drive where the application is mounted G:.beaker or whatever drive.

**Comment by altavir** [comment]
I think that it is better to use beaker own directory since it won't contaminate external directory structure. The best solution is to allow user to configure paths via configuration files or add additional path parameter to `beaker.command` since it covers all possibliies.

There is also a problem with portability comming from the fact that JVM shipped with beaker is 64-bit and some systems still have 32-bit operating system.

**Comment by scottdraves** [comment]
OK within the application then.

agreed about the 64/32 issue, this is a doc bug first https://github.com/twosigma/beaker-notebook/issues/1498, will address for this release.

**Comment by aakinlalu** [comment]
I am considering using portable because corporate firewall. Do I have to install languages I need in the portable folder or thumb drive?

**Comment by scottdraves** [comment]
they can be anywhere, on thumb drive or not.

BeakerNotebook.com
ScottDraves.com
twitter.com/Scott_Draves
