### ISSUE TITLE
use shared memory for autotranslation

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2814]
at least for large objects, maybe small ones faster to just copy.

**Comment by scottdraves** [comment]
or maybe this https://github.com/wesm/feather

**Comment by scottdraves** [comment]
actually, for the in-memory access use https://arrow.apache.org/
feather would be for going to disk.

**Comment by sparkofreason** [comment]
Possible alternative to JSON, particularly for non-columnar data: https://github.com/cognitect/transit-format. I suppose another potential advantage with transit is that it types the entire data graph, rather than just having a single type at the top-level (and I'm making the possibly incorrect assumption that Beaker currently has the latter as a constraint). Not sure how useful that would actually be in practice.
