### ISSUE TITLE
latency for some UI actions is high

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2901]
even for medium sized notebooks like "interactive charts", some UI actions such as clicking on the menus have intolerable latency of 0.6s or so.  this seems to be a regression in the past week.
other actions that are effected; toggling cell visibility, toggling lines with the chart legends.
actions that are not effected: typing and editing in the code mirror, evaluating cells.

**Comment by tomca32** [comment]
Introduced in this commit: 931727704238c526302a709034a2ba3b39befc71

**Comment by tomca32** [comment]
So the issue is with the CSS selector performance. For the last couple of years most people are saying that CSS selector performance is not an issue in modern browsers and we should stop thinking about it.

I guess we just proved otherwise.

**Comment by samccone** [comment]
interesting, the selector in this case as far as I understood was being passed into sizzle and the node was being looked up there, not by CSS.

by caching the element as you did I could see a potential perf boost, however I would be suprised if it was so signifcant. 

I would :heart: to see some numbers (timeline trace) because this is a really interesting case.

**Comment by tomca32** [comment]
Fair point. Didn't realize it was sizzle going through that but now that I think about it makes sense that it was js lookup because it was doing class switching.

Anyway the impact was pretty significant, here are the timeline dumps:

Not cached: https://www.dropbox.com/s/0bj84mjxu1jebco/timeline_not_cached?dl=0

Cached: https://www.dropbox.com/s/raa1vep5iohp9rk/timeline_cached_element?dl=0

Both are using performance notebook which you can find here: test/notebooks/performance_notebook.bkr

I just clicked on the top dropdown menu, going from file to help and back.

**Comment by samccone** [comment]
So I took a look into the traces and well this is really interesting 

So in the cached version we are only looping one time.. in the clearMenu jquery each loop:

![screenshot from 2015-11-10 13 09 33](https://cloud.githubusercontent.com/assets/883126/11075917/a8d2fa14-87ac-11e5-9990-bf06fbe96aa6.png)

on this line:

https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/vendor/bower_components/bootstrap-sass/assets/javascripts/bootstrap.js#L784

VS the uncached version

![screenshot from 2015-11-10 13 09 15](https://cloud.githubusercontent.com/assets/883126/11075948/d38401fe-87ac-11e5-8593-f559cfa709db.png)

which we are hitting ~~3 times~~ (maybe > 3 times but maybe less would need to console.count to be 100%)... and at 1 second per pop, it makes sense why it seems so so slow :turtle: 

I would guess that this new version is actually doing something quite different than before, which might be worth some investigation... 2 ideas
1. the old selector was incorrect, and grabbing too many things to close
2. the new selector is incorrect, and not grabbing all of the elements to close (https://github.com/twosigma/beaker-notebook/pull/2904/files) <-- :smile_cat: 

Due to my past experience around the menu stuff, I would make sure to be doubly sure all the menus close / open when clicking on a new one.

---

As for the reason why  each of these is taking > 1 second, it looks like the parent() call is to blame, on top of the "large" notebook that is already squeezing you memory wise

---

Further perf idea, perhaps consider writing your own clearMenus method and passing in the elements directly, instead of using $parent to walk up the tree (which is the costly bit)

well awesome perf work here @tomca32 and thanks for posting the numbers!

**Comment by paulirish** [comment]
Clickable timeline urls: for convenience:
<strong>
- [Not Cached](https://frontend.chrome-dev.tools/serve_rev/@5fc94bb7460d68729b80640137f454284dba2bba/inspector.html?loadTimelineFromURL=https://dl.dropboxusercontent.com/s/0bj84mjxu1jebco/timeline_not_cached?dl=0)
- [Cached](https://frontend.chrome-dev.tools/serve_rev/@5fc94bb7460d68729b80640137f454284dba2bba/inspector.html?loadTimelineFromURL=https://dl.dropboxusercontent.com/s/raa1vep5iohp9rk/timeline_cached_element?dl=0)
  </strong>

**Comment by paulirish** [comment]
The quick things that I see:

![image](https://cloud.githubusercontent.com/assets/39191/11078355/3477135e-87ba-11e5-94ca-9215f6166c5e.png)

`getParent` in dropdown bootstrap appears to be grabbing the absolute selector. [It is not element-rooted](https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/vendor/bower_components/bootstrap-sass/assets/javascripts/bootstrap.js#L776) and therefore the `>` doesn't make sense and yeah.. should be invalid.

![image](https://cloud.githubusercontent.com/assets/39191/11078181/251f7794-87b9-11e5-9f43-584c13f445b5.png)

What's happening inside all this mess? 99% of it is jQuery thrashing with this selector. I think I remember hearing jQuery team saying they really hit a slow path when a selector string  starts with ">". Their source is littered with `needsContext` conditions, which may be related. I'm not sure, tbh.

But it's definitely clear that jQuery hits major issues here. and I wouldn't be surprised if there are actual bugs in Sizzle here. like ones similar to https://github.com/jquery/sizzle/issues/315
