### ISSUE TITLE
plots should support java.awt.Color

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2931]
instead of producing this error:
https://pub.beakernotebook.com/#/publications/56452db0-4487-4f64-b516-1e60bce455b3
in addition to our own color class.

**Comment by altavir** [comment]
In fact if you are basing on Java 8, I recommend to use [JavaFX Color](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/paint/Color.html) instead of Swing. It is much more flexible and has an advanced [string value parser](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/paint/Color.html#valueOf-java.lang.String-).

**Comment by scottdraves** [comment]
we need to support 7 and 8 so sticking with old classes for now.

**Comment by altavir** [comment]
Well, currently JavaFX is included in jvm7 so it should also work in java 7.

**Comment by scottdraves** [comment]
awt done.  will leave issue open for java FX at a future date.
