### ISSUE TITLE
cat() in R

### ISSUE THREAD

**Issue by mathsong** [twosigma/beakerx#2945]
no output for the function cat() in R
then using print(), the previous output displayed.

https://pub.beakernotebook.com/#/publications/56470b17-8778-4b34-9c92-1cf996e3b957

**Comment by scottdraves** [comment]
thanks for the report.  yea that's because the string returned by cat has no newline,
so the output doesn't show up until it gets one from the print.  here's another report: https://github.com/twosigma/beaker-notebook/issues/699

we were going to fix this when we redid the output handling to go into cells instead of the tray, but i think it fell off the bottom of the queue, thanks for reminding us.

**Comment by scottdraves** [comment]
at the end of evaluation, should make sure the output is flushed and displayed.
if it is not newline terminated should show it with a red null/empty symbol, like github does.

**Comment by mathsong** [comment]
I see. It's ok for me then -- just to add "\n". Thanks for help.

It's hardly a bug for my need for a notebook.

**Comment by scottdraves** [comment]
glad you can workaround it but we can and should handle this more intuitively.
