### ISSUE TITLE
try tangle

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2988]
http://worrydream.com/Tangle/

make a notebook that uses this and try to publish it.  i found it did not work a long time ago but i can't find the issue for it, so making a new one.  does it still have a problem and can it be fixed?

**Comment by scottdraves** [comment]
i found the old issue for this: https://github.com/twosigma/beaker-notebook/issues/850
on our current pub server: https://pub.beakernotebook.com/#/publications/5659bcfb-d54d-42af-9005-49bd6e20d7f9

**Comment by mnavasiolava** [comment]
the problem is that we are trying to update model from DOM, that was modified by tangle.
tangle builds in helper elements to DOM (e.g. hint div).
in this example root element is <p>, tangle adds <div> element inside the paragraph. this is illegal according to the HTML spec. that’s why when we tries to update our model with such html it becomes broken.
if we change root element to <div> html will not be broken after updateDocumentModelFromDOM

but there still be the problem with tangle because the events will not rebind to the new elements.
so may be we can just skip updating from DOM for tangle?

**Comment by mnavasiolava** [comment]
new example with div instead of p
https://pub.beakernotebook.com/#/publications/566b06b7-2705-41e7-afad-a6a31e66c700

**Comment by scottdraves** [comment]
thanks.
