### ISSUE TITLE
clicking on code does not reliably close menus

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3034]
if you open a menu (top, cell, etc) and then click on a code cell, the menu should close.
this is not happening reliably, so there seems to be a race condition.

**Comment by tomca32** [comment]
This is why:
https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/components/notebook/codecell.jst.html#L26

There must be a reason why is stopPropagation there. @mnavasiolava do you know why do we need that?

**Comment by tomca32** [comment]
So it's not a race condition but a super specific set of conditions that causes this:
- A dropdown menu must be open that doesn't belong to this cell (main dropdown or a dropdown from other cell)
- the codemirror must not be focused
- click on a line of code but after the code - in the whitespace
- code mirror gets focus but the dropdown stays open

Removing the event.stopPropagation from the above linked line of code fixes the issue.

**Comment by mnavasiolava** [comment]
@tomca32 about event.stopPropagation. 
If we click inside the output cell but outside the code textarea then we should focus cm editor and set up cursor at the first or last position.
for this purposes there is backgroundClick function on parent div. but this function should not be called if we click inside cm div that's why there is an event.stopPropagation on cm div.

as a solution we can check in backgroundClick function that event target is not cm div and remove event.stopPropagation from the div then

btw, i can't reproduce this bug

**Comment by tomca32** [comment]
I can't reproduce this anymore.
