### ISSUE TITLE
disconnects

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3041]
on mac, open the R tutorial, leave it open for a couple of hours, I get:

```
Uncaught TypeError: Cannot read property 'close' of null_self.onMessage @ cometd.js:1095
webSocket.onmessage @ cometd.js:934
```

**Comment by scottdraves** [comment]
seems related: https://github.com/twosigma/beaker-notebook/pull/3016/files

**Comment by mnavasiolava** [comment]
on windows after 1.5h got the error

```
WebSocket connection to 'ws://127.0.0.1:8801/1d328ae/beaker/cometd/' failed: Error in connection establishment: net::ERR_NETWORK_IO_SUSPENDED
```

**Comment by tomca32** [comment]
After hour and 5 minutes got disconnected.

I see that we are sometimes getting 402 errors in the websocket frames. That causes a disconnect but usually there is a reconnect right after. Here's an example (times are not part of the json, that's just additional info I dug out):

Client:

``` json
[{"channel":"/meta/connect","connectionType":"websocket","id":"147","clientId":"j158ulmp9qd7opgt7awf1wdxzz"}] - time: 14:20:42.228
```

Server: 

``` json
[{
  "advice" : {
    "interval" : 0,
    "reconnect" : "handshake"
  },
  "channel" : "/meta/connect",
  "id" : "147",
  "error" : "402::Unknown client",
  "successful" : false
}] - time: 14:20:42.232
```

So that's the error, now comes the reconnect:
Client:

``` json
[{"version":"1.0","minimumVersion":"0.9","channel":"/meta/handshake","supportedConnectionTypes":["websocket","long-polling","callback-polling"],"advice":{"timeout":60000,"interval":0},"id":"148"}] - time: 14:21:39.080
```

Server: 

``` json
[{
  "minimumVersion" : "1.0",
  "clientId" : "k1n885wpiiv6ut1g2a7t59nmuf7",
  "supportedConnectionTypes" : [ "callback-polling", "websocket", "long-polling" ],
  "channel" : "/meta/handshake",
  "id" : "148",
  "version" : "1.0",
  "successful" : true
}] - time: 14:21:39.082
```

So OK, something caused a 402 but we reconnected, although a full minute later. This happened a couple of time during this one hour session.
Here's the last message exchange when the reconnect failed (take a look at the times):

Client:

``` json

[{"channel":"/meta/connect","connectionType":"websocket","id":"162","clientId":"k1n885wpiiv6ut1g2a7t59nmuf7"}] - time: 14:27:11.201
```

Server:

``` json
[{
  "advice" : {
    "interval" : 0,
    "reconnect" : "handshake"
  },
  "channel" : "/meta/connect",
  "id" : "162",
  "error" : "402::Unknown client",
  "successful" : false
}] - time: 14:27:11.210
```

That's pretty much the same error as before. Now here comes the reconnect:
Client:

``` json
[{"version":"1.0","minimumVersion":"0.9","channel":"/meta/handshake","supportedConnectionTypes":["websocket","long-polling","callback-polling"],"advice":{"timeout":60000,"interval":0},"id":"163"}] - time: 14:28:58.284 (almost two minutes after the error)
```

Server:

``` json
[{
  "minimumVersion" : "1.0",
  "clientId" : "l7lqhssyqto6t1suwq831rpmju",
  "supportedConnectionTypes" : [ "callback-polling", "websocket", "long-polling" ],
  "channel" : "/meta/handshake",
  "id" : "163",
  "version" : "1.0",
  "successful" : true
}] - time: 14:28:58.306
```

And succeeds, everything seems fine BUT just after the client sent the reconnect message, like literally one milisecond after(and before the servers id:163 response, it sent this:

``` json
[{"channel":"/meta/disconnect","id":"164"}] - time: 14:28:58.285
```

So that made it disconnect.

It seems that we are not trying to reconnect until a minute after the error and the last reconnect almost 2 full minutes after the error.

**Comment by tomca32** [comment]
So the underlying problem here is that the server sometimes responds with 402 Unknown client error. The reason why this is happening is that the client doesn't send a new meta/connect message(heartbeat) in a specified time (interval). When there's no meta/connect message in time, the server will delete the state associated with the client and if the meta/connect message arrives after that, server will have no knowledge of that client and will respond with 402:Unknown Client.

As stated here: https://docs.cometd.org/current/reference/#_javascript_configure the default maxInterval is 10 seconds.

Here is the screenshot of websocket traffic before the error:
![screen shot 2015-12-15 at 10 38 49 am](https://cloud.githubusercontent.com/assets/3384784/11815066/18c68ff8-a318-11e5-8daf-c5e2f3aac68f.png)

The selected frame in that image is almost 12 seconds after the last server response so it's too late and the server already deleted the client state so the response is 402:Unknown client

**Comment by scottdraves** [comment]
that sounds right.  now i remember in the python plugin i had to add a keepalive:
https://github.com/twosigma/beaker-notebook/blob/master/plugin/ipythonPlugins/src/dist/ipython/ipython.js#L130
we can do the same for the notebook websocket.
