### ISSUE TITLE
Notebook gets locked up when (accidentally) rendering large outputs

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#3104]
I sometimes accidentally print or display something too large, and it freezes the notebook. In the worst cases, the browser tab's contents disappear altogether (perhaps after switching between browser tabs). Other than extreme caution, is there a way to avoid getting locked out of a notebook? 

Ideally, the notebook could differentiate between computation time and render time, and allow you to abort a render if it's taking more than a couple seconds.

**Comment by tomca32** [comment]
Thanks for reporting this. Optimizing rendering is something we are aware of and trying to improve. However I don't think I've seen lockups before. Is there some sort of example you could share that we can try out?

I don't think we'll be able to abort rendering, simply because of the way browsers work. We can definitely prevent lockups though, so if you could help us out with an example that would be great.

**Comment by scottdraves** [comment]
yea we can probably do better at this with general optimization of the client. if you can provide a test case for tomislav that would be useful. 

we do have a plan to address the root cause of this problem as follows: https://github.com/twosigma/beaker-notebook/issues/2835
we plan for this to be implemented by april.
