### ISSUE TITLE
ubuntu virtualenv install

### ISSUE THREAD

**Issue by jjgalvez** [twosigma/beakerx#3472]
Hi, not really an issue, but not sure where else to leave this. I downloaded and installed beaker 1.5 on ubuntu gnome 14.04. I reviewed your install scripts, and edited them so that both ipython and py3k are installed in virtual environments rather then using the system python install. I try not to put to much into the system level python.  I copied the beaker-notebook folder to ~/opt and within it created two virtual environments, one for ipython and one for py3. I edited the install-dependancies.sh file accordingly. To make things work I edited the beaker config file, and also edited the included python files replacing #!/user/bin/python with #!/user/bin/env python. and lastly I created a shell scrip which added the ipython bin folder to the front of the path before calling beaker.command. I tied it up with a .desktop Beaker launcher.  The only issues I ran into is that roxygen2 is missing from the R install, and I had to comment out the error log entry in the nginx conf file. That is most likely because I had previously had nginx working for another project.

Thanks and great project, please consider changing your install to use virtual environments for both ipython and py3, or giving users a choice at install. Also please include a .desktop launcher so that the application can be easily launched. It's still launched within a terminal window because I don't see any other way to easily kill all the processes that get launched, but again that is not really an issues.

Thanks again
Jose

**Comment by scottdraves** [comment]
Hi Jose, thanks for the feedback.  Asking questions here in github is fine.

Indeed roxygen2 is an issue https://github.com/twosigma/beaker-notebook/issues/3445
IMO some R package is missing a dep because we don't use it, but I guess we have to cover for this problem.

I think editing the included python scripts (you mean xxxPlugin files, right?) should not be needed, they should be happy with the system python.

The shell script that manipulates the path before launching should not be required because the beaker.prefs.json file can specify the path for each backend.

And for the desktop file, we have an electron version that has a more complete GUI including this.

**Comment by jjgalvez** [comment]
Thanks, when I tried it without altering.g the path the plugins it wouldn't work because it was using the system python. Admittedly I edited the plugin files before Iwent just tried it with the altered path. I'll give the electron version a try.
Jose

-------- Original Message --------
Subject: Re: [beaker-notebook] ubuntu virtualenv install (#3472)
