### ISSUE TITLE
download electron

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3633]
it appears we download electron with every build.
if the file exists we should just use it.

**Comment by altavir** [comment]
I think that you also should consider modular installation. Current beaker distribution is about 600 Mb and includes every possible feature. Also it includes the whole JDK, which does not make any sense since JRE is usually installed on all platforms and JDK is not used outside build process.
Also, usually one does not use all possible language plugins, but selects 2-3 of them. 

In future, I hope that beaker will have module manager with separate versions for different modules like it is done in [JAS3](http://jas.freehep.org/jas3/).

**Comment by scottdraves** [comment]
yes the downloads are too big. agreed, the plan is to make them "a la carte" see https://github.com/twosigma/beaker-notebook/wiki/Refactoring
