### ISSUE TITLE
API to load another notebook

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3688]
resulting from discussion with @kyotov and @ildipo:

users often have a problem where they want to share code between notebooks in a less formal way than moving the code into a regular module.  an easy way to get this is to define a function on the beaker object that imports another notebook, and then evaluates its init cells.  ie:

```
beaker.loadLibrary("......").then(.......)
```

library notebooks can be developed to define useful functions in their init cells, and then document and demonstrate them in regular cells.
the loadLibrary function should be able to take a list.
it should only load each lib once (keep a table as it goes).
it should work on a URI that beaker can open.

before implementing this, should check how it interacts with the module systems of the underlying languages.  it it possible to define a proper python or R module from inside a beaker notebook?
maybe not necessary but should not be uninformed on this point.

**Comment by altavir** [comment]
In order to do so properly, you will need cell dependencies an cell references, because initialization cells are rather bad way to indicate which part of the notebook is loaded. To top it all, user can not control when initialization cells are loaded (If cell loads slowly, it is very inconvenient).
On the other hand, if you have cell dependencies, you can reference not the whole notebook, but a specific cell, and then this specific cell and its dependencies are loaded when needed.

**Comment by scottdraves** [comment]
we don't want to reference a specific cell.  perhaps someday we'll have dependencies between cells and then this API can be extended to include a cell tag in addition to a notebook URI.  as far as i can tell what you are asking for is a superset of this plan, so this is a good place to start.

**Comment by altavir** [comment]
> as far as i can tell what you are asking for is a superset of this plan

This is not quite correct. In fact, you should make an ideological decision about whether you want to use notebook or cell as your main structural element and adhere to this decision. The example of bad similar decision is java packages. Sun intended them to be major structural element, but in practice they are used only as name spaces and package private visibility modifiers always never used.

In my opinion, notebook is not very good structural element, because it does not have definite way to know which of its elements are calculated and which of calculated ones are up-to-date. Additionally, notebook can and usually does contain some additional cells, which does not matter for particular calculation. How to decide which cells to run? Currently you want to use initialization cells only. But what if you want to run non-initialization cell or if initialization cells have conflicting global state change?

Each cell changes global state, which is bad for dependency integrity as itself (and one do not control the order of cell execution, which is bad squared). Currently the only way to make results reproducible is to line up all cells and call them one after another. Initialization cells do not have the same order of execution as notebook, so there will be a great mess, when one will try to define what his notebook does or how to reproduce some result.

**Comment by kyotov** [comment]
I might be missing something, but my understanding is that initialization cells are evaluated in the order the appear in the notebook. So "evaluating a notebook", defined as evaluating all its initialization cells in order, will work (for me) as a Phase 1 feature. 

Cells modifying global state is tricky but it is not a new phenomenon. Python packages can modify global state when they are imported... With too much expressiveness you always have to have a healthy judgement and responsibility.

I would put a disclaimer that I come from an environment where each "notebook" had effectively a single cell (they were the same thing) and so I might be a bit naive in my way of thinking notebook dependency is enough. But on the other hand, putting dependencies on the individual cells inside a notebook seems like an unnecessary complication to me (at least on the surface).

**Comment by altavir** [comment]
There may be "normal" cells between initialization cells. So "run all cells" in general does not give the same result as initialization run. Also if one notebook calls another one with an initial global state of its own, then two subsequent runs of external notebook could provide completely different results. Some problems could be solved with reset and rerun option, but it complicates things.

Global state is necessary evil in script languages, but uncontrollable global state change must be avoided where it is possible.

I am working on dependency-based data analysis system (with an aim to make analysis 100% reproducible), so my opinion is also biased. But I think that Beaker developers should carefully consider this point since it could define future development vector.

In fact, there is another option. If notebook is an object and could be operated as one, than external notebook could be another instance of this object with its own beaker class and global state.
