### ISSUE TITLE
indicate word wrap

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3744]
with a turn-back arrow, similar to how we show tabs.

**Comment by sshkalikov** [comment]
For tabs, it shows tags with class 'cm-tab' so we can set background image for this class
But it doesn't do anything with long sequences of chars. Browser wraps lines himself just because CM has CSS-property "word-wrap: break-word;". So it isn't obvious how to determine the place where the line breaks.
[Screenshot form chome dev tools](https://i.gyazo.com/7143246ae2aae33ce793d6ed4ff6d47d.png)

**Comment by tomca32** [comment]
Fair Point. Finding line breaks in a word-wrapping container is tricky, and there is no obvious solution.

However, here's an example of how it can be done: http://jsfiddle.net/pH79a/218/

I don't recommend rushing to use this solution. It introduces a lot of complexity and might have severe performance implications. Especially, if we are going to run it while the user is typing.

I think we should hold off on this. It's not a simple problem and can introduce bigger problems down the road. The benefit, while nice, is not spectacular and not worth it IMO.

**Comment by scottdraves** [comment]
no practical way to do this.
