### ISSUE TITLE
bokeh no longer works

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#3903]
with v11 it does not complete loading.
v10 has some API changes that break our tutorial examples but that's not a big deal.

**Comment by sshkalikov** [comment]
We've already limited version of iPython to 3.x because of the issue #3892. Looks like bokeh v.0.11 isn't compatible with 3.x version of ipython - i always get an error from them ("No module named 'IPython.paths'")
so for now we probably have to set bokeh version to the version _0.10_ compatible with ipython 3.x, until we can't use the latest ipython version

**Comment by scottdraves** [comment]
what about now that the container has latest ipython? can you revisit bokeh 11?

**Comment by sshkalikov** [comment]
just tested it on my ubuntu with ipython 4.2 and bokeh 0.11 - it works
in docker image there's no bokeh at all, but it works if you install it there
