### ISSUE TITLE
Error message in output should be shown inside cell borders

### ISSUE THREAD

**Issue by aryzhykova** [twosigma/beakerx#3934]
Error message in output should be shown inside cell borders

Please see attached screen
http://joxi.net/52avo5OTWDn7A0

**Comment by scottdraves** [comment]
regular output does the same thing, not just errors.
this was working as intended but maybe it should wrap, it's a good question.
we recently changed input cells to wrap instead of making a scrollbar.

if we do make them wrap, there should be an option for showing the full width (like we did for inputs).
i guess with the scrollbar in the output area instead of using the main one.

**Comment by scottdraves** [comment]
has this been fixed?

**Comment by sshkalikov** [comment]
output is wrapped after #4161
![](https://i.gyazo.com/d4fa15690b82de42f90b48aa15ad4135.png)
