### ISSUE TITLE
adding CORS header directly to R-server, scala-server ...

### ISSUE THREAD

**Issue by nguyenxuantuong** [twosigma/beakerx#4432]
Hi,

Instead of using nginx as reverse proxy, what i want to do is patching the http webserver being used by evaluation REST server such as R-server, scala-server, etc... so that it will allow CORS domain http request. (For example, those headers are: Access-Control-Allow-Origin, etc...).

Can anyone please suggest me where to add so that it has effect to every backend services (instead of adding at nginx layer). I know that from security point of view, it's not recommended. But my user case is different.

Thank.

**Comment by scottdraves** [comment]
You could alter the servers for R and Scala since they are in our code, but not the IPython ones like Python and Julia.

The servlets are configured here: https://github.com/twosigma/beaker-notebook/blob/master/plugin/scala/src/main/scala/com/twosigma/beaker/scala/module/URLConfigModule.java

I guess you would put something in there.
