### ISSUE TITLE
Modular plugins through the use of Docker containers

### ISSUE THREAD

**Issue by kennyjwilli** [twosigma/beakerx#4814]
As mentioned [here](https://groups.google.com/forum/#!topic/beaker-user/opKD0KUHZUY), having plugins be distributed as a docker container would modularize plugin development. Each docker container would contain all of the dependencies that the language needs in order to run. When starting the container, you would provide the port to the docker RUN command and the language's docker image would do any other initialization it needs. 

Another benefit of this approach would be a huge reduction in the base Beaker image size -- languages would include their dependencies in their own image, instead of one massive image.

**Comment by altavir** [comment]
I think that first step is to to have modular maven/gradle artifacts. They could pluged-in via OSGI or just by beaker restart. Then one can use these artifacts in docker or any other platform.

I, personally do not use docker, so jar granularity is much more important for me.

**Comment by scottdraves** [comment]
plugins in containers is a good idea but indeed that's only good for those who are into containers (not so much on windows for example).

Alex, can you explain what you mean about modular gradle artifacts?  you mean the ability to load jars from maven into a backend?  I thought you could already do that with grape?

**Comment by altavir** [comment]
Grape works but you can't load beaker components this way.

I mean that beaker itself is not modular. The first step is to separate APIs and implementation. For example, If I want to write my own plugin or even small helper library (which I do want), I need to clone the whole beaker source tree and work in it. 

Now suppose I have API abstraction in separate maven artifact (say plots API). I write my library or module (custom plots - for example scatterplots with error bars) and then just load it into beaker without building the whole thing (just add it to class-path by hand or by OSGI-magic). Then you can maven-like dependency management for such modules. The example of such framework is [Jas3](http://jas.freehep.org/jas3/). Distributing beaker basic plugins the same way makes sense. For now it is overly confusing since most of plugins are presented in the distribution but do not work out of the box.
