### ISSUE TITLE
putting laptop to sleep triggers disconnected dialog

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#486]
Say I am running beaker and have a notebook open.
If I close my laptop, wait a bit, and then open it up again.
Then i try to edit a cell.
I get the "Disconnected" dialog, even though it is still actually connected (I can even type and evaluate cells even though the dialog is up).

**Comment by scottdraves** [comment]
@anglee can you comment please? IMO this is a showstopper bug.

**Comment by anglee** [comment]
I agree this can be improved and it is a valid concern anyway.

When we talked last week, we agreed that once the client is disconnected, beaker should not trying to connect due to it would require extra work to implement telling apart the situations of server restarting and session availability and react properly. But right, at the time, none of us thought of this laptop sleep issue. 

Note that right now the user should be able to just reload the page, or go to the control panel and go to the session to workaround. So I wouldn't consider this a showstopper.

We have a couple action options. We can fix this by putting in the proper connection status detection and reconnecting code. We can add a reload button, label it "Try reconnect" to the dialog, however, it won't work (won't fail properly) if the server really is gone or restarted. Or we can revert my change.

**Comment by scottdraves** [comment]
should be easy for the server to generate a uuid when it starts, and load this into the client when it first connects, and just test for match to avoid talking to the wrong server. this is actually the first step to solving our cache problem too.  anyway, reconnection shouldnt be necessary as i see evaluation continuing fine.

**Comment by scottdraves** [comment]
maybe this should be done with the cache defeater -- let's talk more before you start please.

**Comment by scottdraves** [comment]
It's important that if we detect disconnection and then reconnect successfully (according to comet) that the dialog not pop up and obscure the whole screen.  This would be too visually jarring for users even if it is brief. And this is not something that IPython does for example.

To prevent this, we should use the status area in the upper right to say "connecting..." or something like that when we first detect a problem, and then give it a couple of seconds to clear up.  Only then, if it does not, bring up the dialog and block the window.

If the user tries to interact while "connecting" then bring up the dialog.  But if they do nothing, then let it pass.
