### ISSUE TITLE
Groovy extension module support

### ISSUE THREAD

**Issue by kno10** [twosigma/beakerx#4903]
Adding a groovy extension module to the classpath does not work.
The extension methods are not available in Groovy cells (both the `META-INF/services/org.codehaus.groovy.runtime.ExtensionModule` resource and the classes are, so the jars are available, just not early enough for Groovy?)

Extension methods are nice: essentially you can define a static helper method like `public static String quote(String self) { return '"'+self+'"'; }` in a helper class, but then access is as if it were a class method of the `String` class as e.g. `"abc".quote()`.

I wanted to use ELKIs `VMath` and `FormatUtil` classes as extension module.
This works in groovysh after adding the required service file `META-INF/services/org.codehaus.groovy.runtime.ExtensionModule`:
```
groovy:000> double[] a = [1,2,3]; a.transposeTimes(a)
===> 14.0
groovy:000> double[] a = [1,2,3]; a.format(", ")
===> 1.0, 2.0, 3.0
```
(equivalent to `VMath.transposeTimes(a,a)` resp. `FormatUtil.format(a, ", ")`)

But I can't get the same to work in beaker notebook.

**Comment by scottdraves** [comment]
thanks for the report.  does it work to copy the jar(s) for the extension into the application?
eg on mac for the electron version that would be: `/Applications/Beaker.app/Contents/Resources/dist/config/plugins/eval/groovy/lib`

**Comment by kno10** [comment]
I tried putting them into `core/config/plugins/eval/groovy/lib`, but they were not added to the classpath when using `gradle run` to launch the notebook (building from git, and not on a Mac).

Adding them to the `CLASSPATH` variable (which contains individual jars, not a wildcard) of `core/config/plugins/eval/groovy/bin/groovy` worked.

**Comment by scottdraves** [comment]
oh OK i didn't know you were running from source.
we probably should use a wildcard.

**Comment by jaroslawmalekcodete** [comment]
I have found a way how to register custom extension from language manager,
but there is one problem, when I register my extension, this extension is available for all sessions.

![screenshot from 2016-11-30 14-30-17](https://cloud.githubusercontent.com/assets/21952713/20755173/475692ae-b70e-11e6-99d8-12e344a6b0bf.png)

![screenshot from 2016-11-30 14-31-17](https://cloud.githubusercontent.com/assets/21952713/20755176/4b55d46e-b70e-11e6-9b90-aa4cb390b2d9.png)


and this is because I am using such method to do this

`((MetaClassRegistryImpl) GroovySystem.getMetaClassRegistry()).registerExtensionModuleFromProperties(props, classLoader, metaMethods);`

and
```
package groovy.lang;
public final class GroovySystem {
   
   static {
       USE_REFLECTION = true;
       META_CLASS_REGISTRY = new MetaClassRegistryImpl();
   }
...
}
```

and `META_CLASS_REGISTRY = new MetaClassRegistryImpl();` 
this is why I cannot register extension per ClassLoader

all my method:

```
private void registerGroovyExtensions(final GroovyClassLoader classLoader, final List<String> classPath) throws IOException {
    for (String cp : classPath) {
      JarFile jar = new JarFile(cp);
      ZipEntry entry = jar.getEntry(ExtensionModuleScanner.MODULE_META_INF_FILE);
      if (entry != null) {
        Properties props = new Properties();
        props.load(jar.getInputStream(entry));
        Map<CachedClass, List<MetaMethod>> metaMethods = new HashMap<>();

        ((MetaClassRegistryImpl) GroovySystem.getMetaClassRegistry()).registerExtensionModuleFromProperties(props, classLoader, metaMethods);
        for (Map.Entry<CachedClass, List<MetaMethod>> metaMethod : metaMethods.entrySet()) {
          final CachedClass c = metaMethod.getKey();
          c.addNewMopMethods(metaMethod.getValue());
        }
      }
    }
  }
```

**Comment by scottdraves** [comment]
thanks jarek, looks like this blocked until we do https://github.com/twosigma/beaker-notebook/issues/4834
