### ISSUE TITLE
[Native Beaker] Does beaker always restrict libraries to 32 bit Win32 applications? 

### ISSUE THREAD

**Issue by lcota** [twosigma/beakerx#5005]
Error Logs:

`-DLL load failed: %1 is not a valid Win32 application.
DLL load failed: %1 is not a valid Win32 application.

ImportErrorTraceback (most recent call last)
<ipython-input-1-2cf57e48bf52> in <module>()
----> 1 import tia.bbg as bbg
      2 dm = bbg.BbgDataManager()
      3 term = dm.terminal

c:\usr\python2\lib\site-packages\tia\bbg\__init__.py in <module>()
----> 1 from tia.bbg.v3api import *
      2 
      3 LocalTerminal = Terminal('localhost', 8194)
      4 
      5 from tia.bbg.datamgr import *

c:\usr\python2\lib\site-packages\tia\bbg\v3api.py in <module>()
      2 from datetime import datetime
      3 
----> 4 import blpapi
      5 import pandas as pd
      6 import numpy as np

c:\usr\python2\lib\site-packages\blpapi\__init__.py in <module>()
      3 
      4 
----> 5 from .internals import CorrelationId
      6 
      7 from .abstractsession import AbstractSession

c:\usr\python2\lib\site-packages\blpapi\internals.py in <module>()
     50                 fp.close()
     51             return _mod
---> 52     _internals = swig_import_helper()
     53     del swig_import_helper
     54 else:

c:\usr\python2\lib\site-packages\blpapi\internals.py in swig_import_helper()
     46         if fp is not None:
     47             try:
---> 48                 _mod = imp.load_module('_internals', fp, pathname, description)
     49             finally:
     50                 fp.close()

ImportError: DLL load failed: %1 is not a valid Win32 application.`

**Comment by scottdraves** [comment]
Hi Luis, not that I am aware of.  Googling[1] that error says that the PATH may need to be updated to include the DLL you need (ie the load failed because it was not found, not that it had a 64/32 mismatch).
If there really is a mismatch, then maybe your python is 32 bit, and you need to replace it with a 64bit one.  I see both sizes on https://www.continuum.io/downloads

[1] http://stackoverflow.com/questions/14629818/importerror-dll-load-failed-1-is-not-a-valid-win32-application
