### ISSUE TITLE
make a scala demo notebook 

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5071]
including widgets
![screen shot 2017-03-17 at 11 07 16 am](https://cloud.githubusercontent.com/assets/963093/24049333/1155e946-0b02-11e7-99b7-a32aee488aad.png)

**Comment by scottdraves** [comment]
basic notebook added, needs widgets: easyform, plots, tables, etc.

see the java widgets demo.

**Comment by scottdraves** [comment]
please continue with this:
tables, output containers, java widgets.

also, move all scala tutorials into their own subdirectory of demoFiles.

**Comment by jpallas** [comment]
The recent commit for this issue moved Scala demos into `demoFiles/scala`.  A couple of examples broke because they look for data files (`.csv`, `.png`, etc.) in the current directory, but those are now in the parent directory.  That makes Scala an exception: none of the other kernels have a separate subdirectory for demos.  Either approach seems fine, but consistency would make it easier to compare or translate demos between languages.  Is there a plan to reconcile this?

**Comment by scottdraves** [comment]
thx for the report, agreed, see linked issue.
