### ISSUE TITLE
use jupyter/jvm-repr to control display types

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5120]
https://github.com/jupyter/jvm-repr

**Comment by scottdraves** [comment]
the MIME classes and our widgets should be registered.

**Comment by hadim** [comment]
Is that already possible to do something similar to that : 

```
  Object result = interpreter.eval(code);
  Map<String, String> resultByMIME = Displayers.display(result);
  Kernel.this.display(resultByMIME);
``` 
?

Can `this.seo.finished()` accept a MIMEType (`Map<String, String>`) ?

**Comment by konstantinTarletski** [comment]
***Displayers.display***

We have similar functionality, but only with different class names and other small differences.

`Map<String, String> resultByMIME = Displayers.display(result);`
similar to 
`MIMEContainer  mimeResult = SerializeToString.doit(result)`

MIMEContainer  is holder for `mime` and `code`

so :
`Map<String, String> resultByMIME`
similar to 
`MIMEContainer  mimeResult`

Also this cannot be used to display widgets, because widgets is actually is Comm object.
And it cannot be represented with static HTML.

If our class `SerializeToString.doit` "detects" widget, it display it at once,
this part cannot be replaced by `MIMEContainer` :
```
    HashMap<String, Serializable> content = new HashMap<>();
    content.put(METHOD, DISPLAY);
    getComm().setData(content);
    getComm().send();
```

But in other cases it works same like `Displayers.display`
It  (`SerializeToString.doit`) can be renamed and extended, because now it works like so:
if it not widget it return result as text :
 MIME = "text/plain"

Exact code:
  ```
public static MIMEContainer doit(Object input) {
    MIMEContainer ret = null;
    if (input != null) {
      if (isWidget(input)) {
        DisplayAnyWidget.display(input);
        ret = HIDDEN();
      } else if (input instanceof MIMEContainer) {
        ret = (MIMEContainer) input;
      } else {
        ret = asString(input); // returns MIMEContainer with type: "text/plain"
      }
    } else {
      ret = Text("null");
    }
    return ret;
  }
```

***Returning multiple result***

Only diference with this code is that `Displayers.display` returns several variants,
but `SerializeToString.doit` just one.

Returning multiple result is good idea, also good idea to allow to users "register" new displayers.
But for now we do not have any functionality that allow to user chose way to display the result.
In this example no any suggestions was prowided in this direction:
```
Object result = interpreter.eval(code);
Map<String, String> resultByMIME = Displayers.display(result);
Kernel.this.display(resultByMIME);
```
Just `Kernel.this.display(resultByMIME);`
But this is the main part, by my opinion.

***Registering new displays***

Something similar to registering new displays, already take place in your system:
in same class `SerializeToString`:
`serializerMap`
and 
`internalWidgetMap`

We can do this part public, but it will need to be redone a little bit.

**Comment by hadim** [comment]
Thank you for the detailed explanation.

Where is the mechanism happening ? Does `seo.finished` take care of running the result Object in the appropriate `SerializeToString.doit(result)` ?

Or do I need to do that before ? and so call to `seo.finished` with a `MIMEContainer` instance.

Also, when are you planning to switch to `https://github.com/jupyter/jvm-repr` ? According to that I might wait for you to redesign your API before try to implement "nice output" in my kernel. If you don't know when I might start the implementation with your actual API.

**Comment by hadim** [comment]
To be more specific is this code correct  with your actual API ?

```java
Object returnValue = null;
returnValue = engine.eval(info.getReader());
MIMEContainer niceResult = SerializeToString.doit(returnValue);
this.seo.finished(niceResult);
```

**Comment by scottdraves** [comment]
The switch is in-progress, I am not sure how long it will take.
I am going to guess a week now.

**Comment by hadim** [comment]
Ok I'll wait for you then !

**Comment by scottdraves** [comment]
http://jupyter.readthedocs.io/en/latest/reference/mimetype.html
https://github.com/jupyterlab/mimerender-cookiecutter
https://ipython.org/ipython-doc/3/api/generated/IPython.display.html

**Comment by scottdraves** [comment]
eg this has to go:
https://github.com/twosigma/beakerx/blob/07f8f8f4b3a962374c3fc9d2bae2d36de16d2eca/kernel/base/src/main/java/com/twosigma/beaker/widgets/DisplayAnyWidget.java

**Comment by scottdraves** [comment]
I am still trying to decode this:
https://github.com/twosigma/beakerx/blob/07f8f8f4b3a962374c3fc9d2bae2d36de16d2eca/kernel/base/src/main/java/com/twosigma/beaker/widgets/internal/InternalCommWidget.java

**Comment by scottdraves** [comment]
SerializeToString used to work essentially by returning HTML with embedded JSON and a JS fn call to instantiate it.  What happened to that and why is it no longer possible?

**Comment by gnestor** [comment]
@scottdraves asked me to explain how display works in ipython (so ignore me if you already know this). There are 3 ways to display data in ipython:

1. Use `IPython.display.display({MIME_TYPE: VALUE}, raw=True)`
2. Include an `_ipython_display` method on an object that calls `display()` like in #1. See an example of this in the ipywidgets base widget class: https://github.com/jupyter-widgets/ipywidgets/blob/897976f9d4bb43ef764692e6ddde410c8cf8811c/ipywidgets/widgets/widget.py#L610-L627
3. Include a `_repr_json_` property (e.g. for JSON mime type) that returns a string (no metadata) or tuple (`data, metadata`). See an example of this in ipython's magics: https://github.com/jupyter-widgets/ipywidgets/blob/897976f9d4bb43ef764692e6ddde410c8cf8811c/ipywidgets/widgets/widget.py#L610-L627

ipywidgets uses #2 so that if a return value of a cell is a widget (e.g. `IntSlider()`), ipython will inspect the object and see that it has an `_ipython_display_` method and call it, which in turn calls `IPython.display.display()` using the `application/vnd.jupyter.widget-view+json` mime type. Therefore, beakerx kernels can and probably should take the same approach and inspect return values for a _display-like_ method, that if present, will do the necessary display work for the object. In order to display widgets, the `application/vnd.jupyter.widget-view+json` must be used (because widgetsnbextension is registered with the notebook to render that mime type).

**Comment by scottdraves** [comment]
Thanks Grant.  What it looks like we are doing to create a widget is sending a message like this:
![screen shot 2017-04-20 at 8 03 52 pm](https://cloud.githubusercontent.com/assets/963093/25257251/b7030640-2604-11e7-8c67-059930dc51df.png)

**Comment by scottdraves** [comment]
hm it looks like the json is sent twice.  here it is again:
![screen shot 2017-04-20 at 8 12 01 pm](https://cloud.githubusercontent.com/assets/963093/25257391/b5b0aa3a-2605-11e7-9421-e83ceee350a2.png)

both this message and the previous one came from running a single `new Plot()` cell.

**Comment by scottdraves** [comment]
fixed by https://github.com/twosigma/beakerx/pull/5764
