### ISSUE TITLE
Remove tablesaw dependency from core (make optional)

### ISSUE THREAD

**Issue by kno10** [twosigma/beakerx#5194]
Tablesaw is a beast. It looks harmless (seemingly no dependencies), but that is because it is a **fat jar**, that includes _copies_ of many many large dependencies.

This will eventually cause major version problems, when the user wants to use a newer version of any of these dependencies, and you end up having multiple versions on the classpath.

https://github.com/lwhite1/tablesaw/blob/master/pom.xml

Some (first order only) of the dependencies "secretly" coming with tablesaw:
- antlr 4.0.7 <-- beaker uses 4.5
- guava 19.0 <-- beaker uses 18
- gson 2.5
- JavaFastPFOR
- jackson-dataformat-csv 2.7.5
- commons-collections4 4.0
- commons-math3 3.6.1
- commons-lang3 3.3.2
- opencsv 3.8
- snappy 0.4
- RoaringBitmap 0.6.5
- fastutil 7.0.10
- smile-plot 1.2.2
- xchart 3.2.0
- smile-core 1.2.2
- h2 1.4.193

It would be better to use a **lean** dependency instead.

**Comment by scottdraves** [comment]
agreed it is an expedient solution.
thanks for making an issue for it.

**Comment by scottdraves** [comment]
plan:
1) move tablesaw from deps of the kernel to just a file in demoFiles
2) add it to the classpath of the tablesaw demo ipynb.
3) make a new jar that installs tablesaw as a jvm-repr Displayer.
4) also add this jar to classpath.

**Comment by scottdraves** [comment]
depends on https://github.com/twosigma/beakerx/issues/5120

**Comment by hadim** [comment]
Any idea when tablesaw are going to be removed from the base kernel ? Are you also planning to remove the treelayout dep ? 

That would be awesome to keep the base kernel as small as possible in term of deps.

**Comment by scottdraves** [comment]
It's going to take a couple of weeks unfortunately.  Turns out there are some problems in our widget architecture need to be fixed first: https://github.com/twosigma/beakerx/issues/5277

Not sure what you mean about treelayout, what's that?

We should be easily able to remove antlr4 though: https://github.com/twosigma/beakerx/issues/5317

**Comment by hadim** [comment]
I thought treelayout was a deposit as well but I might be wrong.

I'll wait then.

**Comment by scottdraves** [comment]
i do see org.abego.treelayout.core-1.0.1.jar but we must be getting it indirectly.  does it cause a problem?

**Comment by hadim** [comment]
Well it's the same as for tablesaw.

ImageJ contains a ver important number of different libraries. Each one of them are very carefully managed in order to avoid circular dependency and other dependencies nightmare.

When trying to upload my kernel with its dependencies to ImageJ I have a circular dep issue:

![circular](https://cloud.githubusercontent.com/assets/528003/26132998/07e6aa90-3a72-11e7-90db-23f03a8f54e8.png)

By reducing the number of deps in beakerx, such issues can be easily avoided.

Now I understand Beakerx needs to use third party libraries but I think most of them are needed for high-level things. The base kernel could probably work without any dependencies, except for zeromq of course.

**Comment by scottdraves** [comment]
ok looks like this one is connected to antlr so 3517 should take care of it.

**Comment by scottdraves** [comment]
done here https://github.com/twosigma/beakerx/issues/5702
