### ISSUE TITLE
remove C++ from default build

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5429]
https://github.com/twosigma/beakerx/issues/5420

**Comment by scottdraves** [comment]
1) on mac, this is trivial for most devs since they should already have xcode.
2) on linux, installing clang is easy.
3) the plugin doesn't work on windows, we should not build and install it.

3 is a code change in build scripts, 1 and 2 are documentation for dev dependencies.

**Comment by altavir** [comment]
In my own personal opinion, you should remove as much as possible from default distribution and add additional kernels as plugins. Basically I need only groovy and python, and I am probably not alone.
Clang has a distribution for windows, but configuring toolchains could be a headache. Specifically if one does not use it and does not need it.

**Comment by scottdraves** [comment]
Isn't this what was suggested here? https://github.com/twosigma/beakerx/issues/5135

**Comment by altavir** [comment]
No, it is not. You can make any kind of build from the one repo, just using different gradle tasks or tasks with different parameters. You do not need separate repositories for that. 
I am talking about release distribution whenever it happens. It was a bit annoying in the old beaker to have all this kernel buttons if I need only two or three. It is a minor problem, but distribution size is a problem. For example, you need jdk instead of jvm to allow java kernel. Does anybody use it? Or Node. Why do I need it if I never use it? Etc.

**Comment by scottdraves** [comment]
agreed the kernels should be independent packages.

**Comment by altavir** [comment]
Just tried to reinstall everything. Works without additional problems with standard clang distribution on Windows. Still, I think that it should be removed from minimal distribution.

**Comment by scottdraves** [comment]
cutting C++ from 0.1
