### ISSUE TITLE
gradle for conda forge?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5473]
we need gradle to build our java.
our use of gradlew should auto download the right version transparently.
i don't see how this is any different from yarn downloading various JS packages.

**Comment by altavir** [comment]
In my opinion gradle itself is much more universal than any JS-based tools. There are plugins to call and even auto-download yarn distribution from gradle. In fact, one can completely avoid using anything bat gradle and utilize plugins like this: https://github.com/JetBrains/gradle-python-envs.
It seems that that beaker and beakerx development team is mostly consist of front-end people and moving completely to java-based tooling is not an option. So you are stuck with gradle wrapper. It requires additional few Mb download but otherwise is very stable.

**Comment by scottdraves** [comment]
as per https://github.com/twosigma/beakerx/issues/5476
we only need runtime dependencies in conda.
