### ISSUE TITLE
Upgrading jupyter-js-widgets (ipywidgets 7.0.0)

### ISSUE THREAD

**Issue by gnestor** [twosigma/beakerx#5481]
Once ipywidgets 7.0.0 is released, jupyter-js-widgets will change in a couple ways:

* It will be split up into separate packages (jupyter-js-base, jupyter-js-controls, jupyter-js-html, jupyter-js-manager, jupyter-js-schema): https://github.com/jupyter-widgets/ipywidgets/pull/1400
* It will expect widget state to be in `msg.content.data.state` vs `msg.content.data`. Therefore, if we upgrade jupyter-js-widgets, we will need to update our comm managers accordingly. 
* One other issue to consider is that nbextensions installed outside of a conda environment can (and probably will) be loaded by jupyter notebook inside the conda environment. So if a user has ipywidgets 6 (and consequently jupyter-js-widgets/extension) installed outside of the conda environment, jupyter notebook may load it's nbextension which would not be compatible with our jupyter-js-widgets. This is really an issue with how jupyter paths work. I am tracking this on ipywidgets: https://github.com/jupyter-widgets/ipywidgets/issues/1425

**Comment by scottdraves** [comment]
thx for the report.  we should add a dependency on version 6 until version 7 is released and we update to handle it.

**Comment by gnestor** [comment]
This PR enforces that ipywidgets >= 6.0.0 is not installed: https://github.com/twosigma/beakerx/pull/5486

**Comment by MariuszJurowicz** [comment]
The last commit https://github.com/twosigma/beakerx/tree/mariusz/5481 is the POC for switching to ipywidgets v7.
The major changes are:
- using the `@jupyter-widgets/controls` instead of `jupyter-js-widgets` for the frond end;
- placing the `data` part of comm msg into the `state` property to have the schema of 
```
{
  data: {
    state: {
      _model_name
      _model_module:
      _view_name:
      _view_module:
    }
  }
}
```
- the `metadata` of comm message should contain the `version: 2` property;
- to show widget the message of type `display_data` have to be send with the mime type of eg. `application/vnd.jupyter.widget-view+json` and the content with the `model_id` eg:
```
{
  version_major: 2,
  version_minor: 0,
  model_id: xxx
}
```
where `model_id` is the `comm_id` eg. `this.comm.getCommId()`

**Comment by scottdraves** [comment]
when i run a cell with a widget result i get *two* copies of the widget.
