### ISSUE TITLE
having the words "Cell output" for html cells is really confusing

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#578]
here's how our tutorial starts:
![screen shot 2014-09-06 at 6 52 28 pm](https://cloud.githubusercontent.com/assets/963093/4176840/96fb549e-3618-11e4-9743-163883668cd1.png)
it looks like "Cell output" is a section in the text.

**Comment by melmac48** [comment]
agreed, the cell output label needs to be rethought in general.. however when you are in advanced mode there is no "cell output" label. We can rethink the behavior in v2

**Comment by bradicdesign** [comment]
Since markdown or html aren't really code, the input-output metaphor isn't as valid. Edit / Save metaphor works much better. Rather than doing contortions to make these different types of cells work in exactly the same way, I recommend we treat them as inline editing cells without any output.

Mocks posted on basecamp.

**Comment by scottdraves** [comment]
first step https://github.com/twosigma/beaker-notebook/issues/1360
