### ISSUE TITLE
Chart zooming is broken unless you are scrolled to the top of the page

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#58]
If you scroll down, you can't zoom on charts.

**Comment by anglee** [comment]
Can you provide steps to reproduce this issue?

**Comment by anglee** [comment]
This issue is not Beaker specific and has to do with Chrome's inconsistent behavior(bug?) in different versions and how flotr2 handle scrolling.

flotr2 calculate Y by subtracting both `document.body.scrollTop` and `document.documentElement.scrollTop`:

https://github.com/HumbleSoftware/Flotr2/blob/70064f754f725b58ca68a13437b20aa25c89a1e2/js/Graph.js#L342

I think their reasoning behind this is to address the different behavior of different browsers. More specifically, it is assuming and relying on the behavior of FireFox  where document.body.scrollTop is always 0, and for Chrome, document.documentElement.scrollTop is always 0. ([here](http://stackoverflow.com/questions/20514596/document-documentelement-scrolltop-return-value-differs-in-chrome) is one related stackoverflow post, and as a comment there suggested, a better way is `(document.documentElement.scrollTop || document.body.scrollTop)`).

However, this assumption does not hold true in some version of Chrome. Here is a screenshot comparing Version 35.0.1862.2 canary(lef) and Chrome Version 32.0.1700.107(right). 
![flotr2](https://f.cloud.github.com/assets/1767921/2285046/46cc6f82-9fd0-11e3-89a9-9e2eca3261ea.png)

As one can see, in v32, on the right, both `document.body.scrollTop` and `document.documentElement.scrollTop` has same and non-zero value, and flotr2 code is subtracting the same value twice.

Possible solution would be to fork flotr2 and change it to use the '||' logic mentioned above. Or, do nothing as seems in newer version of Chrome, the old behavior flotr2 depends on returned.

**Comment by scottdraves** [comment]
is this bug what they are talking about here?
https://github.com/HumbleSoftware/Flotr2/issues/235
ang why did you close this?

**Comment by anglee** [comment]
Because like I mentioned A. it is not Beaker specific B. the issue doesn't appear to happen in the latest version of Chrome. As for the issue you referred, it is not exactly the same, but the solution proposed there is exactly what I was talking about.
