### ISSUE TITLE
Run button should become a Stop button when cell is evaluating

### ISSUE THREAD

**Issue by melmac48** [twosigma/beakerx#582]
According to the original design, when a user clicks "Run" the button should change to "Stop" and the color should change to red. Clicking on this while the cell is evaluating should cancel evaluation.

**Comment by scottdraves** [comment]
turns out this doesn't look good in practice.  it produces a red flash that is jarring and makes me feel like an error happened.

if we kept the feature without the color change and just changed the text of the button then i think it would be too subtle.

something like this is possible but let's stick with the current design for now.
