### ISSUE TITLE
not working features for FloatSlider widget

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#5988]
`value` isn't returned
![image](https://user-images.githubusercontent.com/17744188/30541379-d7befab0-9c83-11e7-917e-7b82c042cad4.png)
not working features:
- slider_color
- continuous_update
- visible

**Comment by MariuszJurowicz** [comment]
@scottdraves 
The problem seems to be connected to ipywidgets implementation changes of FloatSlider.
The FloatSlider still has the deprecated `slider_color` property that is not used anymore.
While the IntSlider has the new `style` property that supposed to work now.
To change the slider color use eg. `fs.style.handle_color = 'lightblue'` (the demo file needs updates);
- We have to update our implementation of `IntSlider` and `FloatSlider` widgets to handle the new `style` property.
- We have to check our implementation of comm msgs that handles widgets updates while the `continuous_update` is on.
- We have to check if the `visible` property is implemented in widgets.
