### ISSUE TITLE
needs spinner: when you first open a notebook, it takes a while for the plugins to start

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6]

**Comment by melmac48** [comment]
@anglee can we throw this on the list of work Sam is doing for the new UI?

**Comment by anglee** [comment]
Yes, I think so.

There is already a spinner indicating the 'loading' status, https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/mainapp.html#L40
but I think this issue is more about indicator of whether the plugins are ready. We have been relying on the input cell color change for those.

I am not sure in the new design is, but this is definitely can to be addressed during the new UI impl.

**Comment by melmac48** [comment]
covered by new UI. I'll check when it is released.

**Comment by melmac48** [comment]
fixed with new UI
