### ISSUE TITLE
`sudo pip install beakerx` has some wrong permissions

### ISSUE THREAD

**Issue by dsblank** [twosigma/beakerx#6105]
With latest (0.5.1) I was able to fix with:

```
sudo chmod -R a+r /usr/share/jupyter
sudo chmod a+x /usr/share/jupyter/kernels/*
```

**Comment by scottdraves** [comment]
Hi Doug thanks for the report, what OS did you have this problem on?

**Comment by dsblank** [comment]
Linux (Ubuntu 16.04 LTS 64-bit). Thanks!

**Comment by scottdraves** [comment]
Hi Doug we made 2 fixes:
1) the python package now has python_requires set to >=3, so that you would get an immediate error before it even would try to install into you the python2 env that comes with ubuntu.
2) the permissions of the kernels now respect the umask.  we were creating a temporary directory for staging the kernel before install.  temporary directories are created only readable by the user who created it, and the permissions were copied too.  we now create a regular directory inside the temporary directory, and install from that.

please LMK if this doesn't work for you.
