### ISSUE TITLE
yLowerMargin and yUpperMargin

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6287]
these properties are ignored.  they should take a number of pixels and leave that much space on that part of the graph.  also add a cell to the PlotFeatures.ipynb showing how they work.

**Comment by piorek** [comment]
Sorry @scottdraves, for not being clear on slack.

I made changes, so that when you run:
```js
p = new Plot(title: "yMargins", yLowerMargin: 1, yUpperMargin: 1) 
p << new Line(x: (1..10), y: (5..14))
```
it works the same as running:
```js
p = new Plot(title: "xMargins", xLowerMargin: 1, xUpperMargin: 1) 
p << new Line(x: (1..10), y: (5..14))
```
that was already working. 

Now im not sure, if that one was working as it should, because you wrote:

> they should take a number of pixels and leave that much space on that part of the graph

and as you can see values of xLowerMargin and xUpperMargin are not in pixels (and im not really sure, what are they in).

Is this behavior correct or do I have to make further changes?
