### ISSUE TITLE
simplify DateUtil?

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6307]
https://github.com/twosigma/beakerx/blob/master/kernel/base/src/main/java/com/twosigma/beakerx/util/DateUtil.java

1) needs a banner

2) could overloading be used here to avoiding going back to Object?

**Comment by jmsdnns** [comment]
I looked into this issue.

These two files had calls where the object they pass to DateUtil was properly typed, so a signature could match:
* `com.twosigma.beakerx.chart.xychart.plotitem.Text`
* `com.twosigma.beakerx.chart.xychart.plotitem.ConstantLine`

These three files appear to be called such that they get a map of rows where the key is the column name and the value is simply `Object`. Thus, it makes sense to me why reflection was used.
* `com.twosigma.com.beakerx.chart.xychart.SimpleTimePlot`
* `com.twosigma.com.beakerx.chart.xychart.plotitem.ConstantBand`
* `com.twosigma.com.beakerx.chart.xychart.plotitem.XYGraphics`

As discussed, it may be possible to adjust things so that the types assigned to each column is passed through the system too, but it doesn't seem worth the extra effort at the moment.

Closing.
