### ISSUE TITLE
name tutorials systematically

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#6369]
1) remove the language name from the file name (it is in the path now).
2) remove the word "tutorial" or "demo" or anything like that.
3) use camel case like our java file names.

**Comment by benmccann** [comment]
All the recent docs cleanup has been great! A big improvement!

A few other ideas:
* None of the files in the `cpp` and `nbviewer` directories are linked to from `StartHere.ipynb`
* There's a `doc/contents` folder that's quite out-of-place. It's contents should be moved to be more similar to the others
* I would have left `StartHere.ipynb` in the `doc` folder. If you open the `doc` folder now it can be really hard to know where to start. A user hasn't necessarily looked through all the top-level files. E.g. if you're scanning down the list of files and directories you'll come across `doc` before `StartHere.ipynb` and so may easily open that folder first. I do like that everything else was moved down a level though!
* `StartHere.ipynb` lists some files multiple times. E.g. it has the Scala plotting demo under the `Scala` heading as well as under `BeakerX Plotting in Other Languages`. We could probably remove ` BeakerX Plotting in Other Languages` and just keep the individual language headings?
* Perhaps it would make more sense to have the directories be named after what they're demonstrating rather than the kernel language? E.g. `automation`, `magics`, etc.?

**Comment by scottdraves** [comment]
Thanks.  

* cpp and nbviewer directories will go away at some point https://github.com/twosigma/beakerx/issues/6436 https://github.com/twosigma/beakerx/issues/6224
* i don't see doc/contents it was already deleted right?
* I hear you on this point.  i have found it saves me a lot of clicks to have it here but I know where it is too.  let's get some more feedback on this.
* what's wrong with multiple links? there is more than one way to organize the info.
i do agree it's confusing to mix the topical and language things.  
* i prefer using the kernel since it is clearer.

**Comment by benmccann** [comment]
* yep, looks like doc/contents has been deleted now
* nothing wrong with multiple links in general. I do wonder about the particular heading `BeakerX Plotting in Other Languages`. One option with that header that could make sense would be to perhaps put it right after "Groovy Plotting and Charting" or make it be a sub-bullet of it. We could probably also have the "Scala" and "Python" headings be sub-headings of the "Languages" bullet
