### ISSUE TITLE
need cell execution feedback when output is hidden

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#645]
if i evaluate a cell whose output is hidden i don't get any feedback that it is running and completed.

**Comment by melmac48** [comment]
@bradicdesign can you take a look at this and recommend a behavior.

**Comment by bradicdesign** [comment]
This shouldn't be the case. The Run / Stop button is in the code cell so you should see the progress regardless of the output expanded/collapsed state. I think this wasn't implemented quite this way originally so that may have been the issue. Here is a mock:

![running](https://cloud.githubusercontent.com/assets/6478279/4957710/1eaed992-66a7-11e4-9b52-482df7e2dec2.png)

**Comment by ildipo** [comment]
This might be outdated: now you have the status message in the top bar.

**Comment by scottdraves** [comment]
that doesn't tell you if it got an error or not

**Comment by scottdraves** [comment]
this was done at some point.
