### ISSUE TITLE
Alignment on toolbar differs between cell types

### ISSUE THREAD

**Issue by jchendy** [twosigma/beakerx#677]
First image is markdown, second is Python. In markdown, the toolbar is slightly below the center of the whitespace, in Python it's slightly above center.

![screen shot 2014-09-22 at 10 24 20 am](https://cloud.githubusercontent.com/assets/1740497/4357692/6895d522-4264-11e4-9964-5b3d1f8831bd.png)

![screen shot 2014-09-22 at 10 24 45 am](https://cloud.githubusercontent.com/assets/1740497/4357697/6bd649e2-4264-11e4-8882-a0173199c5b0.png)

**Comment by buob** [comment]
I think this is by design because the markdown cells don't have a title bar/language icon.  We can change it, the markdown cells just look a little emptier toward the top.

Currently: 
![screen shot 2014-11-19 at 11 36 19 am](https://cloud.githubusercontent.com/assets/986404/5109598/4e35155e-6fe0-11e4-9700-3177077a5e9f.png)

With matched padding: 
![screen shot 2014-11-19 at 11 37 06 am](https://cloud.githubusercontent.com/assets/986404/5109608/6afdd1f8-6fe0-11e4-9a69-68b6d5012d86.png)
