### ISSUE TITLE
Integrate rCharts, rMaps, ggvis and Shiny for R

### ISSUE THREAD

**Issue by abresler** [twosigma/beakerx#693]
Haven't tested shiny but tries the other 3; would be amazing to get these working to allow for cutting edge graphics and potential server side controls.

Great work already team Beaker is amazing

**Comment by daveholtz** [comment]
This would also be very useful for our group who is trying to use beaker.

**Comment by scottdraves** [comment]
thanks dave, how would you prioritize these packages?

**Comment by daveholtz** [comment]
Given the way our group uses these packages, the priority is probably something like:

1) ggvis
2) rCharts
3) googleVis (not included in original issue subject)
4) Shiny
5) rMaps

Reasoning is:
It seems like ggvis is slowly (but surely) replacing ggplot - or at least that seems to be the plan.  We use rCharts quite a bit for making interactive charts, and when not rCharts, we use googleVis.  We use Shiny a lot to make interactive dashboards - Shiny is (in my opinion) a bit strange to embed into a notebook, since it operates under the assumption that you are setting up a server and a UI, but you can use Shiny in RMarkdown, so maybe it is possible in this context as well (e.g., http://rmarkdown.rstudio.com/authoring_shiny.html)  For most anything regarding maps, we typically use ggmap (rather than rMaps).  

Thanks for taking a look at this!

**Comment by scottdraves** [comment]
let's start with ggvis.

**Comment by scottdraves** [comment]
OK I looked into how this would work.  ggvis produces a vega spec.
you can capture the spec:

```
save_spec(layer_points(p), "/tmp/myspec")
```

then read it out of the file, return it to the client, and then use a vega output type to display it.
we have had a vega output type in the past, hopefully not hard to revive it.

to make this more automatic we can set the ggvis.print method to just return the spec.

**Comment by scottdraves** [comment]
yup here's the plugin:  https://github.com/twosigma/beaker-notebook/blob/e52bb819f09119827557e3d69d78ad40a13f93cc/core/src/main/web/outputdisplay/bko-vega.js

**Comment by scottdraves** [comment]
ggvis is done.  filing separate issues for the rest:
https://github.com/twosigma/beaker-notebook/issues/2811
https://github.com/twosigma/beaker-notebook/issues/2812
https://github.com/twosigma/beaker-notebook/issues/2813
