### ISSUE TITLE
Support for Python 3.4 broken

### ISSUE THREAD

**Issue by tanderegg** [twosigma/beakerx#6977]
Hello, in `beakerx/install.py`, line 128, the exist_ok keyword parameter is used.  This parameter was introduced in Python 3.5, and so older version of Python 3 will fail.

**Comment by scottdraves** [comment]
thanks for the report, we'll add the dependency constraints so that doesn't happen.

**Comment by tanderegg** [comment]
@scottdraves If there's interest, `os.makedirs` is supported back to Python 3.2, as described here: https://stackoverflow.com/a/41146954.  We are still on Centos/RHEL 6 for some servers, and in that context EPEL doesn't provide a Python later than 3.4, so this would improve compatibility.

**Comment by scottdraves** [comment]
I don't mind changing one line but I don't have a way to install Python 3.2 and test if the app runs after this change.  If you have already done that or are able to send us a PR then I am into it.

**Comment by jest** [comment]
I just stumbled onto this today. It would be very beneficial to change this one line to retain compatibility with Python 3.4 found in Ubuntu 14.04, still found on many server installations. I know, it's been 4 years since the release, but if it's only this one line...

BTW, it's actually two lines, the second use is in `beakerx/environment.py`, line 50:

https://github.com/twosigma/beakerx/blob/c606af1231eda7974567765e270178ef87c0c969/beakerx/beakerx/environment.py#L50

Also note that according to https://docs.python.org/3/library/os.html#os.makedirs:

> Changed in version 3.4.1: Before Python 3.4.1, if exist_ok was True and the directory existed, makedirs() would still raise an error if mode did not match the mode of the existing directory. Since this behavior was impossible to implement safely, it was removed in Python 3.4.1. See bpo-21082.

So I'm not sure the change to `makedirs()` will work for Python <3.4.1
