### ISSUE TITLE
R output without newline is lost

### ISSUE THREAD

**Issue by renkun-ken** [twosigma/beakerx#699]
When I open an R cell and evaluate

``` r
cat("hello")
```

`NULL` is correctly returned (should be invisible) but the text does not show up anywhere. stdout and stderr are blank.

When I evaluate

``` r
message("hello")
```

`NULL` is also correctly returned (should be invisible) and the message in stderr is correctly redirected.

There might be something wrong with the implementation in R plugin about how stdout is redirected.

**Comment by scottdraves** [comment]
Hi Kun the problem stems from the lack of a newline in the string given to cat().
if you terminate the string, call cat() again with a newline, or use print() then you'll see the output.

But you are right, there is a bug, as the output is lost, instead of being queued for the next newline.

Would this NULL problem be handled by the withVisible() you recommended elsewhere?

**Comment by renkun-ken** [comment]
Thanks! 

I believe the invisible `NULL` problem can be definitely handled by `withVisible()`. I suggest that the R plugin evaluate everything ultimately using this function so that notebook knows whether the result is visible or not.

``` rconsole
> withVisible(cat("hello\n"))
hello
$value
NULL

$visible
[1] FALSE
```

**Comment by scottdraves** [comment]
I looked at this more closely and the output without a newline is not lost, it is just queued the line is complete.

But fixing this is not trivial given the current output handling, which is line-based.

We are going to revamp output handling anyway, I'll close this and make sure it gets addressed as part of that Issue.
