### ISSUE TITLE
IndexError when trying to show an empty pandas dataframe

### ISSUE THREAD

**Issue by manuhortet** [twosigma/beakerx#7123]
```
df_empty = pd.DataFrame({'A' : []})
df_empty
```
That cell will show next error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    916             method = get_real_method(obj, self.print_method)
    917             if method is not None:
--> 918                 method()
    919                 return True
    920 

~/anaconda3/lib/python3.6/site-packages/beakerx/runtime.py in f()
    421     def __get__(self, model_instance, model_class):
    422         def f():
--> 423             display_html(TableDisplay(model_instance))
    424         return f
    425 

~/anaconda3/lib/python3.6/site-packages/beakerx/tabledisplay/tabledisplay.py in __init__(self, *args, **kwargs)
    192     def __init__(self, *args, **kwargs):
    193         super(TableDisplay, self).__init__(**kwargs)
--> 194         self.chart = Table(*args, **kwargs)
    195         self.model = self.chart.transform()
    196         self.on_msg(self.handle_msg)

~/anaconda3/lib/python3.6/site-packages/beakerx/tabledisplay/tabledisplay.py in __init__(self, *args, **kwargs)
     33         self.hasIndex = None
     34         if isinstance(args[0], DataFrame):
---> 35             self.convert_from_pandas(args, types_map)
     36         elif isinstance(args[0], dict):
     37             self.convert_from_dict(args)

~/anaconda3/lib/python3.6/site-packages/beakerx/tabledisplay/tabledisplay.py in convert_from_pandas(self, args, types_map)
    103         for column in self.columnNames:
    104             column_type = self.convert_type(args[0].dtypes[column].name,
--> 105                                             args[0][column].get_values()[0])
    106             self.types.append(column_type)
    107             types_map[column] = column_type

IndexError: index 0 is out of bounds for axis 0 with size 0
```

Trying to display an empty dataframe without beakerx installed will just print "Dataframe is empty". Shouldn't that behavior be kept?

**Comment by scottdraves** [comment]
Thanks for the report.
This has already been fixed and will be released shortly.

On Apr 4, 2018 7:57 AM, "Manu Hortet" <notifications@github.com> wrote:

df_empty = pd.DataFrame({'A' : []})
df_empty

That cell will show next error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py in
__call__(self, obj)
    916             method = get_real_method(obj, self.print_method)
    917             if method is not None:
--> 918                 method()
    919                 return True
    920

~/anaconda3/lib/python3.6/site-packages/beakerx/runtime.py in f()
    421     def __get__(self, model_instance, model_class):
    422         def f():
--> 423             display_html(TableDisplay(model_instance))
    424         return f
    425

~/anaconda3/lib/python3.6/site-packages/beakerx/tabledisplay/tabledisplay.py
in __init__(self, *args, **kwargs)
    192     def __init__(self, *args, **kwargs):
    193         super(TableDisplay, self).__init__(**kwargs)
--> 194         self.chart = Table(*args, **kwargs)
    195         self.model = self.chart.transform()
    196         self.on_msg(self.handle_msg)

~/anaconda3/lib/python3.6/site-packages/beakerx/tabledisplay/tabledisplay.py
in __init__(self, *args, **kwargs)
     33         self.hasIndex = None
     34         if isinstance(args[0], DataFrame):
---> 35             self.convert_from_pandas(args, types_map)
     36         elif isinstance(args[0], dict):
     37             self.convert_from_dict(args)

~/anaconda3/lib/python3.6/site-packages/beakerx/tabledisplay/tabledisplay.py
in convert_from_pandas(self, args, types_map)
    103         for column in self.columnNames:
    104             column_type = self.convert_type(args[0].dtypes[column].name,
--> 105
args[0][column].get_values()[0])
    106             self.types.append(column_type)
    107             types_map[column] = column_type

IndexError: index 0 is out of bounds for axis 0 with size 0

Trying to display an empty dataframe without beakerx installed will just
print "Dataframe is empty". Shouldn't hat behavior be kept?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/twosigma/beakerx/issues/7123>, or mute the thread
