### ISSUE TITLE
%run magic in BeakerX Java kernel?

### ISSUE THREAD

**Issue by agodemar** [twosigma/beakerx#7124]
Hello there.
Currently I am evaluating the possibility to document my software project [JPAD](https://github.com/Aircraft-Design-UniNa/jpad) with BeakerX notebooks. Early tests are [this notebook (Java kernel)](https://github.com/Aircraft-Design-UniNa/jpad/blob/master/Jupyter/JPAD/test/Test_JPAD_2.ipynb), and [this notebook (Groovy kernel)](https://github.com/Aircraft-Design-UniNa/jpad/blob/master/Jupyter/JPAD/test/Test_JPAD_3.ipynb).

A `%run` magic in BeakerX notebooks, running Java and other kernels, would be a great feature.
Similar other magics would be useful as well, for instance `%load` or a cell magic like `%%python`.
Any chance these will be addressed sometime in the future?

**Comment by scottdraves** [comment]
Hi I saw your tweet, much appreciated :)

Instead of `%run` and `%load` we recommend you use your normal IDE (or command-line) to edit and compile your java code, and publish the jars to your local maven repository, where they can be consumed in BeakerX.  We've recently expanded the documentation and support for this workflow, see the section "Location of the Maven Cache and Using a Local Repository" in https://github.com/twosigma/beakerx/blob/master/doc/groovy/ClasspathMagicCommands.ipynb

As for `%%python` I agree this would be quite useful.  We plan on developing a full polyglot kernel from which you can access all the languages https://github.com/twosigma/beakerx/issues/6279, but this would be a separate kernel, one that would probably be implemented in Python.  In fact we already have a `%%groovy` magic implemented for python as a proof of concept for this (http://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/python/GroovyMagic.ipynb).  It's pretty easy to run other kernels from python because the jupyter libraries for managing kernels are themselves in python.  The opposite direction however means reimplementing this API in Java or calling into python from java, or something.  So yea, something in this area on the agenda, but we don't have a specific plan yet.

What would work for you?

Thanks for your feedback and questions.

**Comment by agodemar** [comment]
Thanks for your suggestions, I think a `%%groovy` cell magic in a classic Python kernel notebook would work for me.
Keep it up with BeakerX, great project!

**Comment by agodemar** [comment]
One functionality that I'm looking for is using a notebook to launch other notebooks and collect results and data in the main one. This looks like a common workflow.
Any hint about this?

**Comment by scottdraves** [comment]
Thanks.  IDK about that, but it sounds like a good question for the Jupyter email list:
https://groups.google.com/forum/#!forum/jupyter

**Comment by scottdraves** [comment]
> I think a `%%groovy` cell magic in a classic Python kernel notebook would work for me.

this is already supported, but I know there's at least one issue: https://github.com/twosigma/beakerx/issues/7112
if you find more please let us know.
also will be soon expanding it to %%java, etc: https://github.com/twosigma/beakerx/issues/7130

**Comment by scottdraves** [comment]
ideas:
http://jpype.readthedocs.io/en/latest/install.html#install
https://github.com/bartdag/py4j

**Comment by scottdraves** [comment]
closing in favor of https://github.com/twosigma/beakerx/issues/6279
