### ISSUE TITLE
Support for export to Markdown

### ISSUE THREAD

**Issue by janovergoor** [twosigma/beakerx#713]
iPython allows you to convert notebooks to markdown with the nbconverter tool. It would be awesome to be able to do the same with Beaker.

**Comment by daveholtz** [comment]
This is sort of mentioned in #710, but at least for us this would be a huge help (more so than HTML).  One of the big wins here would be that it makes version control fairly easy, as you can commit and comment inline on the resultant markdown files (instead of trying to wrestle with the notebook JSON files).

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/issues/710

**Comment by scottdraves** [comment]
yea i hear you about version control.

That came up in Issue https://github.com/twosigma/beaker-notebook/issues/397
