### ISSUE TITLE
slow table

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7404]
in the LoD tutorial doc/groovy/LevelsOfDetails.ipynb, in the first cell, remove the HIDDEN value so the table is displayed. it is rather slow, it seems the wide column limit is not kicking in.

**Comment by MariuszJurowicz** [comment]
@scottdraves 
The problem is caused by using the `fillText` canvas API method on every scroll or repaint call of DataGrid.
As this example renders the really big Array (10000 items) as string that has about 32000px width when rendered. To fix this performance issue we can cache the rendered value as image and use it on every repaint call (similarly to HTML renderer). You can see the performance boost when setting the format to `html`.

**Comment by scottdraves** [comment]
OK but why didn't the wide column limit kick in?  Anything more than 1000 chars should be truncated.
See the last example in https://github.com/twosigma/beakerx/blob/master/doc/groovy/BigTable.ipynb

**Comment by MariuszJurowicz** [comment]
The reason the value wasn't truncated is that the value here was treated as Object (as it is the Array of 10000 items) and stringified.
But only the String values were truncated not the object ones. I've created PR that forces the String formatter to also truncate the stringified object values.
