### ISSUE TITLE
spark magic should autoload spark

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7418]
if spark isn't on the classpath, then load the latest version.
add a --version option to allow user to specify.
```
%%spark --version 2.1.1
```

**Comment by jarutis** [comment]
It would be nice to also check if $SPARK_HOME is available and use jars from $SPARK_HOME/jars.

**Comment by jarutis** [comment]
One more thought that I had. It would be nice to specify additional libraries in beakerx.json that are autoloaded with Spark. We run spark on AWS and store data on s3 so together with spark we always need hadoop-aws. We also have our internal library with various helpers which we always load with Spark.

**Comment by scottdraves** [comment]
Thank you for the suggestion, sounds like a good idea.
Need to think about this.

**Comment by jpallas** [comment]
With respect to "latest version", would that be latest version as of build time, or as of run time?  The latter would need something like the `search.maven.org` API, I think, since Maven coordinates can't express "latest 2.x version" (to my knowledge).

Along with the additional libraries question, there's the question of whether loading Spark should include `mllib` by default.

**Comment by scottdraves** [comment]
i meant build time as this is much simpler.
mllib question is open, your input very welcome.

**Comment by jpallas** [comment]
mllib adds an additional 17 poms and 15 jars.  That's the only reason I can see not to include it by default—it will affect the time to load Spark.  I'd rather have it and not need it than need it and not have it, since adding things to the classpath in the middle of a notebook doesn't work very well.

**Comment by scottdraves** [comment]
yea SPARK_HOME is a good idea if it's defined load from there, otherwise use a version defined in the code, including mllib.

**Comment by jaroslawmalekcodete** [comment]
1. "spark isn't on the classpath, then load the latest version." -> done (https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html)
2. "%%spark --version 2.1.1" -> done
3. SPARK_HOME -> done
4. mllib -> done

**Comment by scottdraves** [comment]
awesome!!
