### ISSUE TITLE
cookies are set and never deleted

### ISSUE THREAD

**Issue by ildipo** [twosigma/beakerx#750]
Cookies like username-127-0-0-1-8853 are set but never deleted so after many start/stop of beaker in a short period of time the servers runs out of header space and the system stops working untill you clean the browser cookies cache.

**Comment by scottdraves** [comment]
The console error when this happens looks like

[qtp1443006123-22] WARN org.eclipse.jetty.http.HttpParser - HttpParser Full for SCEP@381eb067{l(/127.0.0.1:49526)<->r(/127.0.0.1:8802),s=1,open=true,ishut=false,oshut=false,rb=false,wb=false,w=true,i=0r}-{AsyncHttpConnection@36572a2a,g=HttpGenerator{s=0,h=-1,b=-1,c=-1},p=HttpParser{s=-1,l=5484,c=-3},r=0}

**Comment by scottdraves** [comment]
when should we delete them?  the ipython code is setting them.  i believe this is not a problem when run natively because it always uses the same port, so it reuses the same cookie name.  but beaker uses different ports, so many cookies are created, and eventually the app fails.

i can't think of any way to be sure the cookie is not legit, so we'll have to just put a cap on their total number, say 10, and if you have more then that, the oldest ones are deleted.  in chrome i can see the dates when they were created, but idk if there is an api to get that.  i guess we could watch as the cookies are created and report them to the server where it could remember them like it remembers recent documents, with timestamps of our own.  so complicated.

it looks like in ipython3 the client JS doesn't do any cookie processing, but maybe we could sanitize the port number without the server noticing?  seems like a longshot.

is there a better way?

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1779
