### ISSUE TITLE
Big int64 is not displayed correctly in Table

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#7722]
The original DataFrame.
![image](https://user-images.githubusercontent.com/824507/43317136-3ea016d4-91ce-11e8-957c-3c3bb022b2c9.png)
Displayed as using TableDisplay. As you can that the big int64 numbers are rounded.
![image](https://user-images.githubusercontent.com/824507/43317144-4731c0cc-91ce-11e8-948a-b8dc21c0faa1.png)

**Comment by LeeTZ** [comment]
Thanks @dclong, we will look into that

**Comment by rkrn** [comment]
I can confirm we're experiencing the same thing. This bug generalizes to `datetime64[ns]`, `int`, `np.uint64` etc.

This bug seems to branch differently for datetime fields as opposed to integer fields. In @dclong's example above, we were able to workaround this bug and get the least significant digits displayed by right-clicking the field (e.g. `cmpgn_id` in his screenshot) and choosing to format as string.

However for datetime fields, formatting as string still doesn't help - they remain truncated after the 1 millisecond resolution, even if you format as `datetime[ns]`.

**Comment by piorek** [comment]
@LeeTZ I think this one can be closed
