### ISSUE TITLE
wrong type of data (Table API)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#7945]
see http://localhost:8888/notebooks/doc/groovy/TableAPI.ipynb
![image](https://user-images.githubusercontent.com/17744188/51973686-3c2cc100-248f-11e9-9915-282fd508b19f.png)

see the file with data  ../resources/data/interest-rates.csv
there are
> "m3","y30","y1","m6","y2","y10","y3","time","y5","y7","spread"
> "7.8981","8.2586","7.9210","7.9562","8.0852","8.2067","8.1324","1990-01-30 19:00:00.000 -0500","8.1195","8.1962","0.3086"
> "8.0021","8.5037","8.1111","8.1211","8.3705","8.4732","8.3868","1990-02-27 19:00:00.000 -0500","8.4247","8.4758","0.4711"
> "8.1700","8.5632","8.3500","8.2800","8.6268","8.5886","8.6273","1990-03-30 19:00:00.000 -0500","8.6005","8.6482","0.4186"
> .......

Why the column "y30" has type `string` but another columns ("m3", "y1" etc) have type `double`?
I would expected for "7.8981" and "8.2586" the same type of data in table.

**Comment by EfimovVladimir** [comment]
This bug is for Groovy kernel
Python kernel doesn't have this problem

**Comment by jaroslawmalekcodete** [comment]
@LeeTZ 
The problem is related with "NaN" value in [interest-rates.csv](https://github.com/twosigma/beakerx/blob/master/doc/resources/data/interest-rates.csv)
look at 148 line
```
"1.8250","NaN","2.5670","2.0565","3.5575","5.2840","4.1420","2002-03-30 19:00:00.000 -0500","4.7380","5.1365","3.4590"
```
The "NaN" value is from python world,  java doesn't have it, for java "NaN" is just a String.
The question is how we should treat such case?

Possible solutions:
1. nothing to do, because user should prepare the correct values, e.g. user should convert "NaN" to null if he needs it
2. we can convert "NaN" to null but what if user doesn't want it

**Comment by LeeTZ** [comment]
We will not convert NaN, or Infinity if user provides values like that.
