### ISSUE TITLE
Possible classpath issue for Groovy

### ISSUE THREAD

**Issue by dclong** [twosigma/beakerx#8020]
The code example below doesn't work in the Groovy kernel but it works well in the Scala kernel.

![image](https://user-images.githubusercontent.com/824507/55050127-62dd2300-500c-11e9-8f68-15bd32aeb3bb.png)

**Comment by jaroslawmalekcodete** [comment]
To fix this problem we had to add[ BxDriverManager](https://github.com/twosigma/beakerx/blob/master/kernel/runtimetools/src/main/java/com/twosigma/beakerx/BxDriverManager.java) class in PR https://github.com/twosigma/beakerx/pull/8033
You can use it in the following way 
`%classpath add mvn org.xerial sqlite-jdbc 3.27.2.1`
`conn = BxDriverManager.getConnection("jdbc:sqlite:sample.db");`

**Comment by dclong** [comment]
@jaroslawmalekcodete Mind to explain a little bit on why BxDriverManager is needed? Is it due to the fact that Groovy is a scripting language?

**Comment by jaroslawmalekcodete** [comment]
Hi @dclong 
The problem is in [DriverManager.java](https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/java/sql/DriverManager.java#L208) , the [caller](https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/java/sql/DriverManager.java#L640) doesn't return our bx classloader but the groovy classloader and this is why we added [BxDriverManager.java](https://github.com/twosigma/beakerx/blob/master/kernel/runtimetools/src/main/java/com/twosigma/beakerx/BxDriverManager.java)
