### ISSUE TITLE
Empty tables (classic notebook)

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx#8265]
The table doesn't work on classic notebook:
![image](https://user-images.githubusercontent.com/17744188/78789490-dfdc0000-79b5-11ea-9ffb-672aec95661b.png)

notebook version:
```
# Name                    Version                   Build  Channel
notebook                  6.0.3                    py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
```

**Comment by piorek** [comment]
@ildipo I've talked with @jaroslawmalekcodete and i'll try to investigate what have broken and revert only that

**Comment by piorek** [comment]
@jaroslawmalekcodete @ildipo 

Error is caused by one of those packages
- @phosphor/datagrid
- @phosphor/datastore
- @phosphor/widgets

I had to pin those package versions to the highest known working one. 
We will be replacing them with @lumino/* ones and then I will unpin them. 

As I had to check package by package investigating this issue I updated many devDependencies to highest working version.
