### ISSUE TITLE
File import dialog

### ISSUE THREAD

**Issue by janovergoor** [twosigma/beakerx#830]
Would it be possible for the Mac version to have the file opener default to using the Finder window instead of the build in file browser?

This is probably a dupe.

**Comment by scottdraves** [comment]
I don't know that it is a dupe.  We definitely do plan on redoing the file open dialog since what we have could be improved a lot (I really want sort by mod time).  I don't know if using the native one has been discussed, that's actually a fairly different thing as it means browsing the filesystem on the client instead of the server.  Often those are the same but they could be entirely different.  I have been thinking about supporting drag-and-drop into Beaker, and I think we should do all three of these methods, and consider the design together.

**Comment by bradicdesign** [comment]
I really like the idea of system dialog if we can implement it. However, we still have the issue of opening multiple types so it would require different dialogs (system for files, custom for URI), as illustrated in the mocks.

![opening notebooks](https://cloud.githubusercontent.com/assets/6478279/4961827/fe3526bc-66d3-11e4-8ebf-af9b695073ea.png)

**Comment by scottdraves** [comment]
file dialog needs ability to select sort, either by name or by mod time.

**Comment by bradicdesign** [comment]
There shouldn't be a problem but OS one would be ideal.

**Comment by scottdraves** [comment]
we need both our own and the OS one they are on differing file systems.
