### ISSUE TITLE
Possible race condition about port availability checking and occupying

### ISSUE THREAD

**Issue by anglee** [twosigma/beakerx#88]
As pointed out by @dmitri-at-twosigma: https://github.com/twosigma/beaker-notebook/pull/86#discussion-diff-10724105R177 right now we check the availability of a port and then use it in a non-atomic way.

**Comment by scottdraves** [comment]
this is not a problem in practice and there's no way to fix it so we should recategorize it as wontfix.

**Comment by melmac48** [comment]
@scottdraves can you clarify why this is not a problem. Is it the case that in order to hit this issue two users would have to start beaker at the same time and beaker would have to randomly choose the same port for both users?

**Comment by scottdraves** [comment]
yes two people would have to start two apps at the same time, and both going for the same port.
basically every unix app has this problem and there's no way to avoid it.
it is not a problem in practice.

**Comment by scottdraves** [comment]
To clarify a bit, it actually is possible to have the kernel allocate a port for you and be guaranteed it is free.  You just pass 0 in for the port to bind().  The problem is, we would need nginx to do this and then report the choice back to us.  Maybe it's possible.

We actually could do that for the plugins though, or at least those that we control.

But the bottom line is then you would end up with a random port every time, which means I couldn't reload my browser windows to reconnect to a new server.

So while in theory this could be a problem if you had a shared server with many people running Beaker at the same time, I think it's not worth sacrificing any usability for a phantom problem.
