### ISSUE TITLE
when you add a new language, pop up its config panel

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#911]
in the language manager, if you add a language, and it has a config panel, then select that panel.

**Comment by buob** [comment]
According to the [Angular Bootstrap tabs component](http://angular-ui.github.io/bootstrap/#/tabs) one should be able to set an `active: true` attribute on the object one passes to the `ng-repeat` directive.  We pass in the result of `bkEvaluatorManger.getAllEvaluators()` [here](https://github.com/twosigma/beaker-notebook/blob/master/core/src/main/web/app/mainapp/components/pluginmanager/pluginmanager-directive.js#L55) so can't easily attach that attribute, especially on click of one of the plugin buttons (because the tab doesn't show up until after the plugin is done loading).

Will revisit

**Comment by maxyeg** [comment]
@scottdraves , please check. It works for me. Was fixed in #2982
