### ISSUE TITLE
nginx path needs quotes

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#931]
the following section in the nginx config (and prob others) breaks if there is a space in the path to our static content:

```
location /static/ {
      alias /Users/spot/beaker-notebook/launcher/mac/Beaker mac fix test.app/Contents/Resources/dist/src/main/web/static/;
    }
```

**Comment by scottdraves** [comment]
just got bit by this pretty hard

**Comment by aolney** [comment]
Think I found a variation of this bug:

IPython plugin fails to start when user name has space, e.g. "Andrew Olney"

Repro: create a user name with a space in it (as above), then run default notebook

IPython fails on C:\Users\Andrew Olney.beaker\v1\nginxXXX\profile_beaker_backend_IPython because the file does not exist (probably b/c the path it receives is C:\Users\Andrew

Fixed this by creating user "Beaker", i.e. C:\Users\Beaker.beaker ... and it works

Version is latest 1.1.2-2 windows release

**Comment by scottdraves** [comment]
thanks for the report Andrew. I agree this is the same bug. We will fix it asap.

**Comment by scottdraves** [comment]
https://github.com/twosigma/beaker-notebook/pull/1090
